### ISSUE TITLE
Error with chec

### ISSUE THREAD

**Issue by aurora2346** [veloce/lichobile#1765] opened 2021-07-11 20:37 UTC
![Screenshot_20210711-232744](https://user-images.githubusercontent.com/67618414/125209374-fa7be380-e2a0-11eb-99c4-0dd0b79aba3a.png)

**Comment by jas14** [comment] 2021-07-12 00:01
@aurora2346 please fill out the bug template. We need the following information:

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Comment by jas14** [comment] 2021-07-13 11:04
Duplicate of #1012

**Closed by jas14** 2021-07-13 11:04 UTC
