### ISSUE TITLE
Analysis tab content no longer scrollable

### ISSUE THREAD

**Issue by Avi-D-coder** [veloce/lichobile#946] opened 2019-02-05 22:45 UTC
# Bug report

**Current behavior:**
If the content of an analysis tab is greater than available space the navigation bar is pushed below the screen. Additionally scrolling the contents of the tab is no longer possible.

**Expected behavior:**
Before a recent update I could scroll content in analysis tabs and always see the footer/navigation bar.

**Steps to reproduce:**
Analyze a game, open the opening book at a common position. 

**Environment information**

- phone hardware: Moto G5 plus
- phone operating system version: Android 8.1.0
- version of lichess mobile: v6.1.1

![screenshot 2](https://user-images.githubusercontent.com/29133776/52309330-caacb100-296d-11e9-9fd0-3eaac6992102.png)

Notice How the navigation bar is pushed down by the content.

![9d78e2b7-e2db-4e15-ad12-058c6a3155b3](https://user-images.githubusercontent.com/29133776/52309333-cda7a180-296d-11e9-922d-f5866b4fa72e.png)

**Comment by jpwollan** [comment] 2019-02-06 04:15
Same problem but with Galaxy S9.

**Comment by Avi-D-coder** [comment] 2019-02-06 06:18
I can scroll on the home screen

**Comment by krm01** [comment] 2019-02-06 07:10
same issue, most often on the Game Analysis tab.

LG G5
Android 8.0.0
Lichess v6.1.1

happens both when hiding the navigation buttons and showing them.

![lichess-edited](https://user-images.githubusercontent.com/8379626/52325763-1fb2ec00-299b-11e9-8a46-00e75719130d.png)

**Comment by jpwollan** [comment] 2019-02-06 15:03
Confirmed with a friend on Galaxy S6 that his analysis board is still scrollable with 6.1.1.  My Galaxy S9 scrolling is broken on this release.

**Comment by ScipioWarrior** [comment] 2019-02-06 20:27
Same issue here with a Pixel 2 on Android 9.

**Comment by janierdavila** [comment] 2019-02-09 17:34
I was also having this issue and I was following this for a resolution. Turns out yesterday I got a Chrome browser update and that fixed it. I clicked on other areas in the app and it seems to be working everywhere. My Chrome version now is 72.0.3626.96.

I use a Galaxy S8 un case it makes a difference.

**Comment by Avi-D-coder** [comment] 2019-02-09 18:27
Same here. I think the issue was native scrolling was introduced a few days early. Is this resolved for everyone?

**Comment by niklasf** [comment] 2019-02-09 18:32
The issue was this bug in Chrome (which is used to render the app): https://bugs.chromium.org/p/chromium/issues/detail?id=927066

It has been fixed in the latest Chrome release (`Merged-72-3626`), so if you're still having this issue it should be fixed by updating Chrome.

**Comment by Avi-D-coder** [comment] 2019-02-09 18:37
Thanks @niklasf.
Given that this was a chromium bug I am going to close this issue.

**Comment by Avi-D-coder** [comment] 2019-03-21 05:26
This is broken again. Anyone know why?

**Comment by MartinacPlus** [comment] 2019-03-23 19:03
I also have this problem: vertical scrolling does not work on the Analysis board in any of the tabs (info, the chess notation, Game analysis, Opening explorer).

I tried to uninstall the Lichess app, install it again; uninstall all updates of Google Chrome, installing them again; restart the device multiple times; sacrifice chicken under full moon - nothing helped.

Android version: 6.0, EMUI 3.1
Lichess version: 6.1.1
Chrome version: 73.0.3683.75

My phone is Huawei Honor 7.

Lichess is my favorite chess app, so I'm sorry about this problem since everything else works well...

**Closed** 2019-03-28 09:02 UTC
