### ISSUE TITLE
Can't play since apple update 15.1

### ISSUE THREAD

**Issue by will-iam** [veloce/lichobile#1912] opened 2021-11-13 15:15 UTC
On Apple iphone 12 with IOS 15.1 I can't play a game. Whatever the type of game, the wheel runs for ever and the game never starts. Moreover, I can't play my move in 3-days game. While I validate the move, again the wheel turns for ever and the move is never played. Hope the description helps. Good luck.

**Comment by jas14** [comment] 2021-11-13 15:25
@will-iam thanks for the report. Check out #1898 - does reinstalling the app help?

**Comment by will-iam** [comment] 2021-11-13 19:23
Yes it does, I should have tried it first. Thank you very much for the help.

**Comment by jas14** [comment] 2021-11-13 21:12
Great - marking as duplicate of #1860 for visibility.

**Closed by jas14** 2021-11-13 21:12 UTC
