### ISSUE TITLE
IPad: Option to switch Board and UI Panel view.

### ISSUE THREAD

**Issue by UmutCosk** [veloce/lichobile#1541] opened 2021-02-07 19:47 UTC
Problem:
When I play on the IPad I always have the board on the left and the UI Panels (with the timer, chat and resign buttons etc.) on the right. This is very annoying when doing speed-chess, because my right hand is covering up the timer the notification when my opponent either writes a message, resigns or offers a draw.
As I always hover with my hand over the board, to prepare a fast move, my hand is constantly covering up the timer.
I flagged many times because of this.

Solution:
I would like to have an option in the settings to simply switch the board and the UI panels view. You could call it "left-hand" or "right-hand" mode. I think the current layout is even for left-handers (I am right-handed).

**Comment by jas14** [comment] 2021-03-24 23:16
Thanks for the request! I believe this is a duplicate of #1353 - please close if it is, or update the description if it's not.

**Closed** 2021-04-01 10:40 UTC
