### ISSUE TITLE
Wrong winner reported after times runs out

### ISSUE THREAD

**Issue by duursma** [veloce/lichobile#1823] opened 2021-08-27 14:12 UTC
I played a game on my mobile against DESPedro. Opponent played a bad move and asked for a take-back before I made a move. I accepted. His clock run but apparently was he was not playing.
Suddenly  my clock is on zero and apparently he has moved.  Ok, maybe something wrong in the communication.  But it then reports that white's clock run out (which is my opponent) and therefor white won.  That is wrong by any means.

**Comment by jas14** [comment] 2021-08-29 22:18
Possible duplicate of #1558
Possible duplicate of #1522

**Closed by jas14** 2021-08-29 22:18 UTC
