### ISSUE TITLE
Impossible de promouvoir le pion

### ISSUE THREAD

**Issue by gvanoost-fr** [veloce/lichobile#1739] opened 2021-06-22 07:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

Au moment de promouvoir un pion, il y a un bug d'affichage (Blitz 5 mn).

**Comment by jas14** [comment] 2021-06-25 17:51
Appears to be a duplicate of #1734

**Closed by jas14** 2021-06-25 17:51 UTC
