### ISSUE TITLE
Board theme 'Wood 4' not functional

### ISSUE THREAD

**Issue by Atharva5720** [veloce/lichobile#2365] opened 2023-05-25 07:03 UTC
**Describe the bug**
When board theme is set to 'Wood 4' on Lichess mobile application, the board and its squares are invisible. Just the pieces and highlights on squares are visible.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Board theme'
3. Scroll down to 'Wood 4' and select
4. Start a game or open analysis board
5. See error

**Expected behavior**
When 'Wood 4' selected, expected to be able to see the board with the selected background instead of the void.

**Screenshots**
![Screenshot_20230525_121450_lichess (1).jpg](https://github.com/lichess-org/lichobile/assets/113532864/dd633bc3-687d-43e1-ba58-f20766d80734)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A22 5G]
 - OS: [Android 13 One UI 5.1]
 - Browser [Google Chrome]
 - Version [113.0.5672.132]

**Additional context**
Bug started to occur in this week. The Board background 'Wood 4' was functional before that.

**Comment by jas14** [comment] 2023-05-25 10:25
Duplicate of #2354.

**Closed as not planned by jas14** 2023-05-25 10:25 UTC
Labels: bug
