### ISSUE TITLE
Please add lichess app to https://f-droid.org/

### ISSUE THREAD

**Issue by jim-perkins** [veloce/lichobile#1331] opened 2020-08-09 22:31 UTC
**Is your feature request related to a problem? Please describe.**

https://f-droid.org/
Some users of android do not use the play store.  fdroid supports open source apps and has their own app which will notify the user of updates to their existing apps.  If lichess app was added to froid users could keep it updated automatically

**Describe the solution you'd like**
add lichess open source android app to fdroid ecosystem

**Describe alternatives you've considered**
download apk from this site, but it will not automatically update

**Additional context**
thanks for all your work on the android app

**Comment by jim-perkins** [comment] 2020-08-09 23:37
apparently there are some old issues which are over my head.  Here is some information.
https://lichess.org/forum/lichess-feedback/android-app-on-f-droidorg#4

**Comment by furai** [comment] 2021-01-26 21:01
Would love to see lichess on f-droid. Is there anything I could do to help with that?

**Comment by nfitzen** [comment] 2021-03-18 11:09
Duplicate of #278.

**Closed** 2021-03-20 09:15 UTC
