### ISSUE TITLE
Feature request: Creation of Lobby on menu

### ISSUE THREAD

**Issue by ghost** [veloce/lichobile#1218] opened 2020-05-02 20:29 UTC
**I'm submitting a ...**  (keep the relevant one):
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by jas14** [comment] 2021-12-07 01:40
Duplicate of #1149

**Closed by jas14** 2021-12-07 01:40 UTC
