### ISSUE TITLE
Puzzle rating not updating after returning online

### ISSUE THREAD

**Issue by borbrudar** [veloce/lichobile#2002] opened 2022-01-23 17:34 UTC
I've noticed what appears to be a bug in the mobile app. If you go offline, a batch of 50 puzzles is downloaded, and you're informed that your rating will be updated once you're back online...but that doesnt happen, for me at least. 

Other info:
-Phone: Samsung Galaxy A7(2018) (model nm.: SM-A750FN/DS)
-OS: Android 10
-Lichess version 7.14.1

**Comment by jas14** [comment] 2022-01-23 18:27
Duplicate of #1972

**Closed by jas14** 2022-01-23 18:27 UTC
