### ISSUE TITLE
prevent app from opening certain links

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#1564] opened 2021-02-20 07:52 UTC
Such as blog posts and swiss tournaments. People are uninstalling the app just so they can read the blog or join a tournament in the browser.

**Comment by LichessUser** [comment] 2021-02-20 08:37
Yes, whenever we click to blog or tournament or profile of a player in the browser, it automatically redirects to app instead of opening it into the browser itself.

**Comment by veloce** [comment] 2021-02-20 17:19
those links should not open in the app indeed, looks like a regression

**Comment by veloce** [comment] 2021-02-20 17:36
I can't reproduce so far. Please send more information on how to reproduce. Only the profile link were supported, I don't mind to remove it if it's annoying, so I'll remove it. It make sense to remove it since the profile page in the app is very light compared to the desktop one.

**Comment by freefal** [comment] 2021-02-21 14:56
I can confirm that sending the following link to myself as an SMS and opening it on iOS results in the app being launched and then just showing the the Home Screen. 

Unfortunately I don’t have an iOS dev environment to investigate, but wanted to share if useful in reproducing. 

https://lichess.org/blog/YCvy7xMAACIA8007/fat-fritz-2-is-a-rip-off

**Comment by veloce** [comment] 2021-02-21 18:31
This has been fixed server side, but it needs an app re-install. I'm closing it since there is nothing more to do on app side.

**Closed by veloce** 2021-02-21 18:31 UTC
Labels: bug
