### ISSUE TITLE
fatal error: app uses button navigation area

### ISSUE THREAD

**Issue by trailsandtribulations** [veloce/lichobile#1649] opened 2021-04-14 06:23 UTC
**Describe the bug**
In last two days - whether upgrade in Adroid or Lichess I do not know - the bottom of the screen, the three button navigation area, is being used by the Lichess app.

this means that when you want to chat, resign, or whatever when playing a game, you're instead pressing an Android navigation button. eg, instead of chat you're home.

**To Reproduce**
Adroid 11, security update 2021-03-01

**Expected behavior**
the app screen area should end above the navigation area - or the app buttons should appear in location that does not conflict with navigation buttons

**Screenshots**
sorry

**Smartphone (please complete the following information):**
 - Device: Vivo
 - OS: Android
 - Browser n/a
 - Version 11

**Additional context**
Only began happening Apr 13 Cambodia time

**Comment by jas14** [comment] 2021-04-16 23:08
Duplicate of #1575.

**Closed** 2021-04-17 17:23 UTC
