### ISSUE TITLE
weird game layout with overlapping buttons

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#1813] opened 2021-08-21 11:11 UTC
![](https://i.imgur.com/gwa6hGZ.jpeg)

device: https://www.gsmarena.com/vivo_v19-10134.php

**Comment by ornicar** [comment] 2021-08-21 11:12
the player can't use the resign button

**Comment by jas14** [comment] 2021-08-21 11:13
Duplicate of #1575

**Closed by jas14** 2021-08-21 11:13 UTC
