### ISSUE TITLE
Bug report: puzzle 248425003

### ISSUE THREAD

**Issue by ops-oneiric** [veloce/lichobile#1591] opened 2021-03-10 00:39 UTC
**Describe the bug**
Checkmate results in an incorrect puzzle attempt and lost puzzle rating. 

**To Reproduce**
1. Go to puzzles
2. Find puzzle 248425003
3. Checkmate with queen instead of rook
4. Note incorrect result

**Expected behavior**
Since a checkmate is the best possible result of a move, and all checkmates are equally winning, any checkmate should result in a correct puzzle attempt, and no checkmate should be logically preferred to another. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73957805/110557702-b916d400-8106-11eb-9a79-f6fd19c048ae.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max 
 - OS: iOS 14.x
 - Lichess app

**Additional context**
Possible solution--test for a checkmate result after every move before comparing the attempt to a preordained move sequence.

**Comment by jas14** [comment] 2021-05-12 13:28
Cannot reproduce - I solved this puzzle with what appears to be the same sequence of moves and the app recognized it as correct.

**Comment by jas14** [comment] 2021-12-23 02:11
I'm going to close this as we can't reproduce and generally source puzzles and their solutions from the server. Feel free to reopen if you run into this again.

**Closed by jas14** 2021-12-23 02:11 UTC
