### ISSUE TITLE
Training mode not buffering attempts made while connection is temporarily lost?

### ISSUE THREAD

**Issue by Unihedro** [veloce/lichobile#243] opened 2015-12-21 13:39 UTC
From email:

<blockquote>I played training mode on the app when my connection got lost shortly.

In that time I solved the puzzle. But it still showed 'Best move. Continue' or something like that.

I wondered what else to do and did a move which made me fail and gave me -18 points.

I guess the app couldn't send the final move at the tone I made it and after it regained a connection it did not check of the current state is already correct. So I had to make a (wrong) move to trigger the next check.

After failing the puzzle the piece went back into it's position and there were no moves I could do via the right arrow button (showing the solution) which should prove that I already solved the puzzle.

**Comment by quinncomendant** [comment] 2016-05-02 18:09
Yep, I'm experiencing this too when using *training* mode on an intermittent internet connection. Here's a screenshot that illustrates the problem: notice checkmate has been achieved, but the app is still saying *Best move! Keep going…*. The network connection was offline at the moment the checkmate move was made, and there is no way to recover and continue playing or move to the next puzzle.

![training-no-internet](https://cloud.githubusercontent.com/assets/6884276/14962940/fe0557c8-1066-11e6-94a2-9fa8498167b6.jpg)

**Comment by quinncomendant** [comment] 2016-05-24 22:38
This is not yet fixed, completely. Using the latest Lichess app (v3.0.2) on iOS 9.3.2 on iPhone 6, there is still some undesirable behavior. Here's an example using [chess puzzle 13492](http://en.lichess.org/training/13492):

To start, this is the solved state of the puzzle with internet access (expected behavior): 

![solved](https://cloud.githubusercontent.com/assets/6884276/15521896/10eccd20-21d4-11e6-8360-1b783145d46a.jpg)

Now the same puzzle without network access. Here I've simulated being offline by enabling airplane mode, but I've encountered this many times with the bad 3G internet we have in the mountains here. 

1. At the moment when the puzzle should be solved, it gives the warning “No internet connection. You can still play offline from the menu.” However, instead of announcing *Victory!* it says to *Keep going…*: 

![offline-1](https://cloud.githubusercontent.com/assets/6884276/15521967/8c26cffe-21d4-11e6-9dcb-2d498c360a18.jpg)
2. Despite the puzzle being solved at the previous position, it still allows making another move, and no matter which move is made, the puzzles goes in to a *Puzzle failed* state: 

![offline-2](https://cloud.githubusercontent.com/assets/6884276/15521993/c29166d0-21d4-11e6-9363-3e5a5f25fe1f.jpg)

At this point the puzzle is stuck, with no way to proceed except by going to the menu and choosing *Training* again, which will load a new puzzle (sometimes the same puzzle). 

Expected offline behavior: If the known solution is loaded with the puzzle and available offline, the solution should be marked *Victory* even if offline (although with a notice that the score is not recorded because of the offline state). Ideally, the user score would be synced once network access is resumed. But that's not a big deal, because if the score is not updated, the status of that puzzle is not updated and so the same puzzle will usually be loaded again in the future in which case solving it a second time and adding it to the score is done.

**Comment by veloce** [comment] 2016-05-25 09:27
Thanks for this detailed report. The thing is that the issue is fixed only in version 3.1 which has not been released yet on ios. 

I will test anyway with the puzzle you mention with 3.1 version so that I can confirm it is fixed. My fix is different from the one you suggest: when a failed attempt to send the move because of the network the move will be reverted and it's up to the user to try again when the network is back.

You solution is of course better but it required more work. Maybe on day I'll code fully offline puzzles and so that could be reconsidered.

**Comment by veloce** [comment] 2016-05-30 13:47
Thanks for the report @quinncomendant : I fixed another bug :)

**Closed** 2016-05-30 13:47 UTC
Labels: bug
