### ISSUE TITLE
Home Screen goes blank; unresponsive after 7.0.0 update.

### ISSUE THREAD

**Issue by hhgttg42** [veloce/lichobile#1129] opened 2020-02-07 16:49 UTC
# Bug report

**Current behavior:**

Open the app, browse away from the home screen (click the settings/"hamburger" menu), return to home screen. home screen becomes unresponsive or goes completely black and I have to force-close the app. Also can't click on the active-games icon in the upper right to view current games.

**Expected behavior:**

to be able to browse the app normally, and to see current games by clicking on the current game icon without force restarting the app

**Steps to reproduce:**

open app; start using it; app locks up or goes completely black.

**Environment information**

- iPhone 7 model FN8L2LL/A
- iOS 13.3.1
- lichess v7.0.0

**Other information:**

I have deleted the app from the home screen on iOS, reinstalled from the app store; deleted it from the app storage listing under settings > general > iPhone storage, hard-reset the phone, reinstalled, and the issue persists. I have also made sure to close all running apps to free up system resources. This seems like the same issue as #1123 which was just closed.

**Comment by SuperAtty-github** [comment] 2020-02-07 17:02
I have a similar problem. I try to start a game and all I get is

![FEB9BAB0-D9C8-4FBE-8DAC-F51BE0AE1F0E](https://user-images.githubusercontent.com/60790413/74049210-a7ae4600-49a1-11ea-8772-d4fa5a3334d4.png)

A blank board with the dots showing time is passing and no game

**Comment by arnulfholm** [comment] 2020-02-07 17:13
The blank board is duplicate of
https://github.com/veloce/lichobile/issues/1127

**Comment by colinluthier** [comment] 2020-02-08 22:44
iPhone X with iOS 13.3. Anytime I hit the home button the screen goes blank and requires a force restart. The friends and the current game icons on the upper right are unresponsive. Started with 7.0.0. The only way to make a move it to catch the banner when the notification goes out. Otherwise there is no way to make a move.

**Comment by hhgttg42** [comment] 2020-02-25 13:18
I don't know if this will help anyone else, but I went and revoked a number of stale logins at lichess.org/account/security, and then logged back into the app using the 2FA app (It hasn't asked for that info in a while) I have attached to my account.

Now functionality is seemingly restored. I will post back if it reverts to the original issue.

**Comment by deanellis** [comment] 2020-02-28 17:41
Deleting old logins apparently restored my iOS apps as well; they were completely dysfunctional and now everything is normal.

**Comment by veloce** [comment] 2020-02-28 20:58
So, deleting old sessions fixed the app. Does it mean that when you deinstall an app, ios still keeps the cookies?

**Comment by hhgttg42** [comment] 2020-03-09 17:25
> 
> 
> So, deleting old sessions fixed the app. Does it mean that when you deinstall an app, ios still keeps the cookies?

I can only assume it does? Perhaps clearing the cookies using Safari would have had the same effect. When I revoked the sessions, I was prompted to use my 2FA login after re-opening the app, whereas I had not been prompted to do so when deleting the whole app.

**Closed** 2020-08-31 10:05 UTC
