### ISSUE TITLE
Android app not connecting

### ISSUE THREAD

**Issue by temporarium** [veloce/lichobile#1657] opened 2021-04-23 15:32 UTC
For some days now, my Android app is not connecting to the servers. It shows "**? players**" and "**? games in play**" and "**Ping ? ms**". When trying to do a Quick setup game, it shows "**Reconnecting ...**" with a spinner.

I am on the latest version (7.10.0). Have tried reinstalling the app, wiping cache. An older version (6.3.0) on another device behaves similarly.

I can play in the browser, so I don't think my IP is blocked/banned.

I heard there were problems with the server(s) a few days ago. It that what's happening? Any fix/suggestions from the devs or other users?

**Comment by JobNoorman** [comment] 2021-04-24 18:54
I'm having exactly the same issue.

I just wanted to add that I can login via the app and I do see all my in-progress games. Making moves in those games doesn't work though. Puzzles do work and the score also gets correctly synchronized.

**Comment by veloce** [comment] 2021-05-01 09:05
Duplicate of https://github.com/veloce/lichobile/issues/1599

**Closed by veloce** 2021-05-01 09:05 UTC
