### ISSUE TITLE
App Crashes when I try to change between correspondence games

### ISSUE THREAD

**Issue by gricchio** [veloce/lichobile#1156] opened 2020-03-04 22:28 UTC
**I'm submitting a bug report** 

# Bug report

**Current behavior:**

Whenever I open the application, i will hit the button to view current games in the top right corner. I have 3 games where it is my move so it has a little 3. When I hit this button, 80% of the time it will freeze, screen goes black. 20% of the time i can play my move. After the move is finished, I hit the button again to look at another game, and the app locks up 100% of the time.

**Expected behavior:**
I would expect it to open my game explorer, so that I can select the game that I want to play in.

**Steps to reproduce:**
Open App, open game, if i can load in, make a move. Try to select another game, freezes.

**Environment information**

Phone: Iphone 11 64 gig MWHV2LL/A
Software: IOS 13.3.1
Lichess version 7.0.3

**Other information:**

Have had other friend experience similar issues.

Have restarted the phone several times, have reinstalled the app several times. Not sure exactly how to fix this.

**Comment by gricchio** [comment] 2020-03-14 23:48
Hello, I was able to solve the issue by myself by opening the web client for lichess and clearing my invites section. It looks like it had created  duplicate requests for starting a new game and it was causing the app to crash on my iPhone.

Hopefully this post can help others with a similar issue

**Comment by tholman** [comment] 2020-03-16 04:17
For the love of all that is holy, open this bug up again... had me super confused for over a week.

**Comment by gricchio** [comment] 2020-03-20 14:44
> 
> 
> For the love of all that is holy, open this bug up again... had me super confused for over a week.

Are you having a similar issue? I thought it was complete because I solved the issue?

**Comment by landry314** [comment] 2020-03-30 05:35
i am having this issue too now. i am able to make a move in one correspondence game then when i tap in the upper right to view the next game, it does nothing. i tap and tap... i need to force quit the app then open it again to study the next game.

i tried deleting storage and data and it did not work.

i am using 7.0.4.

this seems to have started after the lichess update yesterday but since this is 10 days ago on this issue then i guess it was a coincidence?

**Comment by landry314** [comment] 2020-03-30 05:39
oooh, ok, i also went to the invites in the web client and i had an open invite stuck in there. i cleared it and it fixed the issue.

this is a bug and needs to be reopened. why did that invite get stuck in there? it was an open invite to a correspondence game which never got picked up...

**Comment by veloce** [comment] 2020-03-31 13:08
Please if you have a way to reproduce it, send it to me (steps, etc.)

**Comment by tholman** [comment] 2020-03-31 13:35
It's a tricky one.  When I had it broken, if I challenged someone to a game it would sit on the challenge screen rather than setting it aside. 

I'll try again later today, I think it has something to do with opening a challenge and then closing the app before some requests have resolved.

**Comment by landry314** [comment] 2020-03-31 19:18
ok, i figured out how to reproduce:

1) make sure you have multiple correspondence games going on
2) in the android app go to the home screen
3) tap on "play with a friend"
4) set it up then tap on "play with a friend" again

on my phone this leads to spinning circle once a small pause then a spinning circle again then a blank screen and a frozen app.

5) force quit the app
6) go back in the app and choose a correspondence game
7) when viewing that game tap on the upper right to try to view another correspondence game

nothing happens... nothing. in fact, the app is crashed, frozen.

8) force quit the app
9) go to a web browser to log into lichess
10) in the challenges menu, delete all the challenges there

this will unfreeze the app, even if it is open and frozen, it will UNFREEZE!

can anyone reproduce this?

**Comment by landry314** [comment] 2020-03-31 19:24
oh, i just figured out something else...

if you create a challenge in the web browser and try to play a friend there it ALSO causes the same problem in the app!

meaning, if there is ANY OPEN CHALLENGE then the android app will freeze as you attempt to switch correspondence games.

**Comment by veloce** [comment] 2020-04-01 08:02
Thanks for this @landry314 . I'll try to reproduce now, and if I can the fix will be easy.

**Comment by veloce** [comment] 2020-05-11 12:30
Couldn't reproduce. Closing then.

**Closed by veloce** 2020-05-11 12:30 UTC
Labels: bug

**Comment by landry314** [comment] 2020-05-11 21:24
Wow, really? This bug sucks. I can not keep open invites open and switch correspondence games after moving. A lot of people have this problem...

**Comment by veloce** [comment] 2020-05-12 09:22
are you sure you are using 7.0.4? can you try delete the app and reinstall?

**Comment by landry314** [comment] 2020-05-12 23:00
> i am having this issue too now. i am able to make a move in one correspondence game then when i tap in the upper right to view the next game, it does nothing. i tap and tap... i need to force quit the app then open it again to study the next game.
> 
> i tried deleting storage and data and it did not work.
> 
> i am using 7.0.4.
> 
> this seems to have started after the lichess update yesterday but since this is 10 days ago on this issue then i guess it was a coincidence?

Yes, i am using 7.0.4 ^^

Yes, i reinstalled the app cleanly. I just did it again to check.

It is still the same. If i create a challenge to share the link with a friend or I have any open challenge with a friend who has not accepted it yet then I can not change correspondence games in the mobile app.

**Comment by landry314** [comment] 2020-05-12 23:06
I think this might have something to do with the way the app organizes games. An open challenge remains all the way to the left until it is accepted. I opened #1045 about this problem. Just a hunch.

The way the app is written to organize challenges and open correspondence games is not so clean. I think it needs a good going over.

**Comment by tholman** [comment] 2020-05-12 23:45
Yeah, I've been able to reproduce again. The open challenge doesn't appear in the app, but can be seen through the browser.

**Comment by veloce** [comment] 2020-05-13 08:16
@tholman if you can reproduce with other steps than what @landry314 provided, can you share them here as well so I can have a look? Thanks!

**Comment by veloce** [comment] 2020-05-13 08:32
@landry314 @tholman can you share here you phone / phone os too? thanks

**Comment by veloce** [comment] 2020-05-15 18:18
I found the bug, I was finally able to reproduce it.

**Comment by tholman** [comment] 2020-05-15 18:21
🙏🙏🙏

**Comment by landry314** [comment] 2020-05-15 22:43
I am using a Pixel 2 walleye with Lineage OS 16 (Android 9).

I'm glad you could reproduce the bug!

I basically can not keep any challenges open and also play correspondence games. Any open challenges whether started in the web browser or in the app just lock up the Android app when you try to switch between games.
