### ISSUE TITLE
Iphone 12 mini lichess app problem

### ISSUE THREAD

**Issue by Ahmedylmz** [veloce/lichobile#1968] opened 2022-01-05 00:15 UTC
I am using iphone 12 mini. At first i do not have problem but after 1 game if i click somewhere, buttons places change. It is not a important issue but it disturbs me a lot. I need to restart the app for each game. As you can see in image so hard to use buttons at the bottom of screen.

I think the other iphone users may have same problem if you bring new update we will be so happy :)

 - Device: [e.g. iPhone12 mini]
 - OS: [e.g. iOS15.1.1]
 - lichess application
 - Version 7.14.1 lichess app
![00D8E46B-09B7-4F35-B8FE-4B19D943DE94](https://user-images.githubusercontent.com/97135528/148140645-a00f0e93-b056-41ee-ba4f-b27cf4d64274.png)

**Comment by jas14** [comment] 2022-01-05 03:25
Duplicate of #1877

**Closed by jas14** 2022-01-05 03:25 UTC
