### ISSUE TITLE
Feature Request: Phone Camera board and piece recognition to play.

### ISSUE THREAD

**Issue by infinitless** [veloce/lichobile#1923] opened 2021-11-23 11:07 UTC
There is SO much of open source code on Github that enables camera recognition and playing chess via a normal (non electronic) chess board. A really good feature to have would be to integrate this code into the LiChess App on iOS and Android such that it uses the phone camera for board and piece recognition and playing. 

This would circumvent the use of a computer/laptop and get rid of all the issues that plague differences in hardware with DGT, Millennium and any other boards!

**Comment by jas14** [comment] 2021-11-23 11:42
Duplicate of #561 - thanks for the input, go ahead and give that issue a thumbs-up please so we can gauge its popularity 🙂

**Closed by jas14** 2021-11-23 11:42 UTC
