### ISSUE TITLE
App tends to crash when reopened after doing puzzles

### ISSUE THREAD

**Issue by inseltraeumer** [veloce/lichobile#1574] opened 2021-02-27 08:24 UTC
If you leave the app after playing a puzzle, it crashes very often upon opening it again after some time. 

**To Reproduce**
1. Do a puzzle. 
2. Leave application. 
3. Have a cup of coffee (or tea, if preferred). 
4. Reopen the application. Very likely, it's going to crash and close again. 

**Expected behavior**
It shouldn't crash when reopened. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 8]
 - OS: [e.g. iOS 14.4]
 - Browser: Safari
 - Version: no idea

**Additional context**
[lichess-2021-02-27-092204.ips.txt](https://github.com/veloce/lichobile/files/6053993/lichess-2021-02-27-092204.ips.txt)

Another crashlog:
[lichess-2021-02-27-131721.ips.txt](https://github.com/veloce/lichobile/files/6054386/lichess-2021-02-27-131721.ips.txt)

**Comment by inseltraeumer** [comment] 2021-02-27 08:42
[lichess-2021-02-27-092204.ips.txt](https://github.com/veloce/lichobile/files/6053986/lichess-2021-02-27-092204.ips.txt)

**Comment by veloce** [comment] 2021-02-27 09:46
Thanks for the report.
Question: do you go to analysis after the puzzle is complete, before leaving the application?
The crash report says the crash has something to do with the stockfish plugin, so if you can I'd like more precise steps (eg what do you do exactly in the analysis screen, like option chosen (memory, cpu, infinite analysis, etc.)
Thanks.

**Comment by inseltraeumer** [comment] 2021-02-27 10:01
I can't remember the last time I used that feature. Is there maybe some analysis going on under the hood while puzzles are played?

I usually just solve a puzzle or two (or fail miserably) and then close the application by hitting the home button.

**Comment by veloce** [comment] 2021-02-27 10:44
Ok, so you don't use analysis. Thanks. I'll try to reproduce the issue.

**Comment by inseltraeumer** [comment] 2021-02-27 10:46
What strikes me when I look at my settings is that it says 185 of 128 (MB, I suppose) of memory. Could that be an issue?

**Comment by veloce** [comment] 2021-02-27 10:56
should not since local evaluation is off. but yes this is another issue.

**Comment by veloce** [comment] 2021-02-28 17:38
duplicate of #1543

**Closed by veloce** 2021-02-28 17:38 UTC
