### ISSUE TITLE
Black pieces arent black.

### ISSUE THREAD

**Issue by porqoff** [veloce/lichobile#1867] opened 2021-09-29 15:52 UTC
Somehow ive logged in and found the pieces are without shadows.
![IMG_20210929_212154](https://user-images.githubusercontent.com/48444617/135304456-0d7a93d9-111a-4194-8c0a-3d4b772d8b74.jpg)

Nothing is helping. 

What can be done?

**Comment by jas14** [comment] 2021-09-29 16:10
Duplicate of #1859

**Closed by jas14** 2021-09-29 16:10 UTC
