### ISSUE TITLE
Dark splashscreen for dark them

### ISSUE THREAD

**Issue by Denis1983** [veloce/lichobile#975] opened 2019-04-15 08:33 UTC
Hi,

I am using the dark theme, but the splashscreen is white.
Could you please make inverted splashscreen (white knight on black background) for the dark theme?

Regards,
Denis

Examples:
Inverted: (for dark theme)
![Lichess_splashscreen_inverted](https://user-images.githubusercontent.com/5038510/56118059-cb635400-5f69-11e9-9f00-95517ff01c7d.png)
Normal:
![Lichess_splashscreen_normal](https://user-images.githubusercontent.com/5038510/56118068-d1593500-5f69-11e9-9074-d84b6b12c1a1.png)

**Comment by Denis1983** [comment] 2019-05-10 17:51
Or even gray, like at start page:
![Lichess_gray](https://user-images.githubusercontent.com/5038510/57546375-ed7ba680-735c-11e9-98dc-2a8e50ad0570.png)

**Comment by superuser-does** [comment] 2019-12-09 10:24
There's been forum feedback concerning this as well: https://lichess.org/forum/general-chess-discussion/blog-XeRN0BAAACAA7HJu?page=20#199

I agree it's worthwhile, it's probably best to follow system preference since I think the user's preference hasn't been loaded at that point. On Android though, this only applies to Android 10+ devices and on iOS, I'm not sure if they have such a thing as a dark theme.

It's best to have two different screens for this, one dark and one light. The reason is that that the flashing effect of going dark system->light splash->dark lichobile is what makes it jarring. It would be equally jarring to go light system->dark splash->light lichobile.

I still love having a splash screen and would like to see it stay on.

**Comment by antonkratz** [comment] 2020-02-11 04:26
> Hi,
> 
> I am using the dark theme, but the splashscreen is white.
> Could you please make inverted splashscreen (white knight on black background) for the dark theme?
> 
> Regards,
> Denis
> 
> Examples:
> Inverted: (for dark theme)
> ![Lichess_splashscreen_inverted](https://user-images.githubusercontent.com/5038510/56118059-cb635400-5f69-11e9-9f00-95517ff01c7d.png)
> Normal:
> ![Lichess_splashscreen_normal](https://user-images.githubusercontent.com/5038510/56118068-d1593500-5f69-11e9-9074-d84b6b12c1a1.png)

Any progress on this? This issue semms to make a lot of sense to me. I play chess mostly (late) at night, of course with dark theme on iOS and for the app, an the white splash screen is quite painful - even with night mode and red shift, and so unnecessary.

**Comment by smcue** [comment] 2021-02-13 02:58
Says merged, but it hasn't been implemented? Would be a welcomed addition.

**Comment by jas14** [comment] 2021-05-24 13:45
Hi all, I know this issue was opened first, but as the other issue has a couple more thumbs-ups, I'm going to close this as a duplicate of #1366 . Please do give that issue a thumbs-up, and continue any discussion over there. Thanks for your feedback!

**Closed by jas14** 2021-05-24 13:45 UTC
