### ISSUE TITLE
Android client won't connect but website will

### ISSUE THREAD

**Issue by xXxDeadStarxXx** [veloce/lichobile#1599] opened 2021-03-15 17:14 UTC
Hi for the last month or so I can't connect to the servers from the Android client, opening a browser and playing from there works fine tho. Interestingly the news feed works fine even in the Android app, but I can't get a ping from the server nor play any games online.
I'm using redmi 7a a10.
I tried deleting then reinstalling the game also reinstalling the system but nothing works

**Comment by axydavid** [comment] 2021-03-18 09:35
I have the same issue. I thought I am the only one with this issue, I don't know what's going on.
Does lichess block certain type of android OS?

**Comment by nussbaumer** [comment] 2021-04-18 09:08
Same problem here, Redmi Note 10 Pro, LineageOS 18.1, no Gapps

**Comment by lukhas** [comment] 2021-04-18 10:22
Hello,

Can you try and tell us precisely when (date and time) you try and see the error? I'll try to see if I can find something in the logs.

**Comment by veloce** [comment] 2021-04-18 10:35
Hi, you could also tell us the lichess app version you are using, that would be helpful. Thanks.

**Comment by nussbaumer** [comment] 2021-04-18 11:05
Last time was CET 2021-4-18 12:49:11, user name wan**, github version 7.10.  I can provide logcat if nessessary

**Comment by veloce** [comment] 2021-04-25 09:58
@nussbaumer logcat would be useful indeed. If you need a debug build to do that, you can find them under "Actions" tab, then "Android build" workflow. For instance: https://github.com/veloce/lichobile/actions/runs/761255995

**Comment by JobNoorman** [comment] 2021-04-27 09:43
This looks similar to #1657 so it might be a duplicate.

**Comment by JobNoorman** [comment] 2021-04-27 10:11
I just ran logcat while starting the lichess app and this caught my eye:

> 04-27 11:57:50.541 29611 29640 D NetworkSecurityConfig: No Network Security Config specified, using platform default
> 04-27 11:57:50.552 29611 29611 D Capacitor/Console: File: http://localhost/lib/socketWorker.js - Line 202 - Msg: [homeLobby k1dh_WQNGj0p] Debug is enabled
> 04-27 11:57:50.553 29611 29611 D Capacitor/Console: File: http://localhost/lib/socketWorker.js - Line 202 - Msg: [homeLobby k1dh_WQNGj0p] connection attempt to wss://socket.lichess.dev/lobby/socket/v4?sri=k1dh_WQNGj0p&mobile=1
> 04-27 11:57:50.555 29611 29699 E Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SecurityError: Failed to construct 'WebSocket': Access to this address is not allowed.","url":"http://localhost/lib/socketWorker.js","line":58,"col":15,"errorObject":"null"}}
> 04-27 11:57:50.557 29611 29611 E Capacitor/Console: File: http://localhost/lib/socketWorker.js - Line 58 - Msg: Uncaught SecurityError: Failed to construct 'WebSocket': Access to this address is not allowed.
> 04-27 11:57:50.593 29611 29611 E Capacitor/Console: File: http://localhost/lib/socketWorker.js - Line 58 - Msg: Uncaught SecurityError: Failed to construct 'WebSocket': Access to this address is not allowed.

The following line also looks suspicious and is repeated multiple times:

> E chess.mobileap: Invalid ID 0x00000000.

I've [attached](https://github.com/veloce/lichobile/files/6383715/lichess.log) the full log.

**Comment by veloce** [comment] 2021-04-29 07:02
thanks @JobNoorman that's very useful

**Comment by veloce** [comment] 2021-04-29 08:40
@JobNoorman could you tell use the device / OS version you are using? Also this bug looks like a client side security measure. 
This application runs on a webview, which normally on android comes with the chrome application. Can you send here also the version of chrome installed on you device?
Thanks.

**Comment by JobNoorman** [comment] 2021-04-29 08:56
Sure!
- Device: FairPhone 3+
- OS: /e/ OS 0.16-q (Android 10, based on LineageOS)
- WebView: Android System WebView 90.0.4430.59. Based on the /e/ browser which is a fork of Chromium/Bromite.

I recently upgraded /e/ (from 0.15 to 0.16) which included an update of WebView so I wonder if that's when the problems started. I'm not entirely sure though because I feel like I successfully used the lichess app after the update.

**Comment by veloce** [comment] 2021-05-01 09:15
Thanks.  Apart from the update, I dont' see what could cause the problem.

I don't know the exact issue yet unfortunately. But someone reported a similar issue in bromite repository:
https://github.com/bromite/bromite/issues/838

Which links to this issue: https://github.com/bromite/bromite/issues/590#issuecomment-738624112
Not 100% sure, but it looks like a security measure was implemented that would block websockets from a web worker (this is a difference between the app and lichess website).

**Comment by JobNoorman** [comment] 2021-05-01 10:41
I might be misunderstanding something but aren't these Bromite issues about preventing gateway attacks on the local network? So these patches are about blocking WebSockets connecting to localhost. The error messages shown [above](https://github.com/veloce/lichobile/issues/1599#issuecomment-827488584) seem to be about connecting to socket.lichess.dev which doesn't resolve to localhost (or any private IP address).

**Comment by veloce** [comment] 2021-05-01 12:37
As I said I'm not 100% sure, but I don't see any other explanation for now. The thing is you first saw this issue some time ago and I'm pretty sure the app code (or the server code) hasn't changed since. So it's most likely not a regression on lichess side.

**Comment by temporarium** [comment] 2021-05-02 14:07
I just thought I'd add this for further consideration....

For some days now (since around the 17th of April), my Android app is not connecting to the servers. It shows "**? players**" and "**? games in play**" and "**Ping ? ms**". When trying to do a Quick setup game, it shows "**Reconnecting ...**" with a spinner.

I am on the latest version (7.10.0). Have tried reinstalling the app, wiping cache. An older version (6.3.0) on another device behaves similarly. All my devices run Bromite system webview.

I can play in the browser, so I don't think my IP is blocked/banned.

I, too, thought that it may have been a recent webview update, but I tried on a device which hasn't had Bromite system webview updated since November, and it had exactly the same issue.

**Comment by archiron** [comment] 2021-05-03 06:51
same for me with 0.16 update on an S9+ with Lichess 7.10.0
application only show "?" for ping & server, not responding on click.
I have tried reinstalling the app, wiping cache for nothing.
When I play with web app (in the browser) I can see the results on the application !

**Comment by JobNoorman** [comment] 2021-05-05 21:24
@veloce I'm trying to report this bug at Bromite (bromite/bromite#1129) but it got automatically closed because I didn't use the latest version. Since it's not trivial to update SystemWebView, I was wondering if there's any way to run lichobile in a browser on Android?

**Comment by JobNoorman** [comment] 2021-05-06 08:19
I think I'm getting a bit closer to the cause of this issue.

When running lichobile in a browser, the Web Worker that is created for the `socketWorker.js` script is created in the context of the index (from `main.js`). If you look at the network tab of the Chrome DevTools, you see that the initiator of the request for `socketWorker.js` is `(index)`.

When running lichobile natively through a WebView, however, the request to `socketWorker.js` has its initiator listed as `Other`, which is also used for the top-level request to localhost so my guess is that this request is directly made from the app, not from `main.js` (although the code to create the Web Worker seems to be there...).

I think the reason Bromite doesn't allow the WebSocket in the second case, is because it is made from an unknown context. It seems lichobile could therefore bypass this issue by makings sure `socketWorker.js` is loaded from the `index` context (i.e., from `main.js`). Is this something that would be easy to try out?

**Comment by axydavid** [comment] 2021-05-07 05:59
I want to confirm that running it on a normal webview causes the app to connect to the server. Same phone, and android version, so I can confirm this is an issue with Bromite's security features.

**Comment by stigok** [comment] 2021-05-12 10:37
> HOWEVER, this would also imply that an older version of Bromite system webview shold work correctly. It does not. My app was working fine till the middle of April. Something changed around that time. I installed the latest 89 version of Bromite system webview (released around the beginning of April) and it does not work either.
> 
> Are you sure there were no changes on the server around the middle of April?

The app stopped working for me at the same time. No ping, and just stops on "Reconnecting" when attempting to join a game.
- Fairphone 3+
- e/os 0.16-q-20210415110657-dev-FP3
- Lichess APK  v7.10.0

**Comment by JobNoorman** [comment] 2021-05-12 10:54
For reference: there is a corresponding [issue at /e/](https://gitlab.e.foundation/e/backlog/-/issues/3055). I've added everything I found out about this issue [there](https://gitlab.e.foundation/e/backlog/-/issues/3055#note_94204).

**Comment by archiron** [comment] 2021-06-17 07:16
now work for me with version 0.17 of /e/ update (8.1.0) on an S9+ with Lichess 7.11.2
Arnaud

**Comment by JobNoorman** [comment] 2021-06-17 08:00
Same for me. Since I believe only /e/ users were having this issue, I think it can be closed.

**Comment by veloce** [comment] 2021-06-17 08:03
Thanks, I'm closing then.

**Closed by veloce** 2021-06-17 08:03 UTC

**Comment by temporarium** [comment] 2021-06-17 15:04
Not a bit premature?
It's still not working for me and I'm not on /e/.
Has anything even been done to address the issue or even find its cause?

**Comment by JobNoorman** [comment] 2021-06-17 15:07
@temporarium It might be premature indeed, I didn't realize people not using /e/ are affected. Which Android distribution are you running and does it use Bromite as its SystemWebView?

**Comment by temporarium** [comment] 2021-06-17 15:15
I'm on Resurrection Remix Android 10, rooted and with microG. I do use Bromite System Webview. Another device is running LOS Android 7, rooted and with microG, also with Bromite.

- https://github.com/veloce/lichobile/issues/1599#issuecomment-830815231
- https://github.com/veloce/lichobile/issues/1599#issuecomment-835372832

As you can see, I've tried older versions of the app and of Bromite.

I've been using the web version since then till this morning when the above reports came in that it was working again. Tried it and still the same - not working.

**Comment by JobNoorman** [comment] 2021-06-17 15:30
Have you tried with a Bromite SystemWebview older than 84.0.4147.106?

As far as I understand, this problem was introduced with [this Bromite issue](https://github.com/bromite/bromite/issues/590) which was fixed by [this patch](https://github.com/bromite/bromite/blob/90.0.4430.101/build/patches/Block-gateway-attacks-via-websockets.patch) which is was first released in 84.0.4147.106. I tried opening a [new Bromite issue](https://github.com/bromite/bromite/issues/1129) but, unfortunately, the Bromite devs are [unwilling to look at it](https://github.com/bromite/bromite/discussions/1124#discussioncomment-711461) as they don't officially support the SystemWebView.

So, I'm not sure if lichobile can do anything about it. If you are able to build Bromite yourself, you could try to disable the offending patch.

**Comment by temporarium** [comment] 2021-06-17 21:02
I tried with v89. I had not issues with any Bromite version up until mid-April, and I've been using the app for a long time. That's why I don't think it is Bromite. And I haven't got a device with regular Android Webview to test :-(

**Comment by JobNoorman** [comment] 2021-06-18 07:09
v89 already had this patch so what you say is consistent with Bromite being the problem. Note that 84.0.4147.106 was released in July 2020 so your earlier comment about a device that was not updated since November and also has this issue is consistent with this theory as well.

**Comment by temporarium** [comment] 2021-06-19 01:15
That's just the point. All my devices kept Bromite System Webview updated. And the Lichess app was running fine till mid-April. Bromite v90.0.4430.59 was released Apr. 7. That's why I tried installing v89.0.4389.117 to see if that's when a change in Bromite System Webview crept in that messed it up. And that didn't help.

You seem to suggest I should go back to before v84.0.4147.106. But then, why was the app working just fine all this time? That's what makes me suspect something else...

I even went back to Android System Webview and still the same.

**Comment by temporarium** [comment] 2021-06-29 20:21
Any ideas what could be adjusted for the app to work? Even if it is Bromite (though, as I mentioned previously, it worked fine for me till just very recently), perhaps this (https://github.com/veloce/lichobile/issues/1599#issuecomment-833331293) can be tweaked? I miss using the app :-(

**Comment by temporarium** [comment] 2021-07-01 17:40
UPDATE: I installed Bromite System Webview v84, and yes the latest app (7.11.3) does work. The version I prefer (6.30) does not.

I am still puzzled as to why both versions worked flawlessly till  just recently, through all the Bromite webview updates.

Is no one else using Bromite System Webview? Are they all stuck on v84 or less?
