### ISSUE TITLE
Feature request:lobby access in mobile app <android>

### ISSUE THREAD

**Issue by tyronevdm** [veloce/lichobile#1945] opened 2021-12-06 12:39 UTC
**Is your feature request related to a problem? Please describe**
I'm asking if it's possible to add the 'lobby' screen in the mobile app , similar to how the lobby page is displayed in the browser,  where there is a bunch of games with people and their rating and you can select one to connect with that person , love ichess ❤ keep up the amazing work 👏 

**Describe the solution you'd like
A clear and concise description of what you want to happen.**

Lobby to be accessible from the mobile app like it is in the browser when you want to see all the users searching for a new game 

> Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

Alternative is I have been using the browser but have been using the mobile app less and less which I find more user friendly than the browser 

Additional context**

**Comment by jas14** [comment] 2021-12-07 13:13
Duplicate of #1149.

I'm closing this as a duplicate of #1149 , as that issue was submitted first. Please do give that issue a thumbs up so we can gauge interest for this request in one place. Thanks!

**Closed by jas14** 2021-12-07 13:13 UTC
