### ISSUE TITLE
Chess puzzles

### ISSUE THREAD

**Issue by znn2000** [veloce/lichobile#1398] opened 2020-10-19 18:59 UTC
The lichess app is giving me the same puzzles over and over and will not give me any new puzzles so I cannot get rating points through the app

**Comment by KLaurence** [comment] 2020-12-02 22:11
Bumping this issue. This also happens to me.

**Comment by jas14** [comment] 2021-12-23 02:12
Duplicate of #1359

Please give that issue a thumbs-up so we can gauge interest - thanks!

**Closed by jas14** 2021-12-23 02:12 UTC
