### ISSUE TITLE
Getting the same training puzzles repeatedly, no score updates

### ISSUE THREAD

**Issue by bilts** [veloce/lichobile#813] opened 2018-04-19 02:33 UTC
This problem persists in a severe way, beyond logging out, clearing data, and reinstalling.

The app shows me the wrong score and it doesn't update as I complete puzzles. It sends me through the same puzzles in the same order, so I don't get new puzzles and my results rarely appear on the website. 

Every once in a while, I'll see some scores reflected or get a new puzzle, but I can't see a rhyme or reason to it.

Puzzles work fine on the website.

**Comment by l3d00m** [comment] 2018-04-22 10:25
This was reported on reddit as well, thought I maybe should leave it here

https://redd.it/8doluf

**Comment by l3d00m** [comment] 2018-04-23 10:09
And this was reported a lot of times in lichess' forums:

https://lichess.org/forum/lichess-feedback/bug-report-puzzle-score-inconsistent-between-android-app-and-website-v550

https://lichess.org/forum/lichess-feedback/bug-mobile-app-android-puzzle

https://lichess.org/forum/lichess-feedback/tactics-bug-when-trying-to-retry-this-puzzle-ios

https://lichess.org/forum/lichess-feedback/lichess-app-puzzle-bug-with-dodgy-internet-connection

I hope it may be helpful to see different report perspectives about this issue

**Comment by veloce** [comment] 2018-04-23 13:25
Ok. I know this issue has been reported several times, but I have not been able to reproduce it so far. It may be a client (app) issue but it may be also a server issue. The offline caching functionality adds complexity.

Now, you must send at least the app version (some bugs have been fixed on latest version) and precise steps to reproduce the problem, or I can't do anything about it.

**Comment by l3d00m** [comment] 2018-04-23 13:39
Sure thing,  I'm on app version  and android version 7 with a S7.

Steps:

1. Open the profile screen, look at the rating there (eg 1400)
2. Open the puzzle screen, check the current rating there via the overflow menu too (in this example it's 1400 as well)
3. Play a puzzle (I won one in my example)
4. Look at the rating via overflow menu again (It updated there this time, sometimes it does not. I now have a rating of 1450)
5. Look at the rating in the profile (it's still stuck at 1400, although it's updated on lichess web. If I restart the app after killing it, it still shows 1400).

My example was executed while having a full internet connection.

This is just one example though, in other cases the rating in the overflow menu does not update or in very rare cases I have duplicated puzzles after a while. For this I can't get you any steps to reproduce though as of now

**Comment by bilts** [comment] 2018-04-23 16:31
I see the same as @l3d00m (score stuck at 1492 now, with no puzzles I complete listed).  No amount of data clearing or reinstallation fixes it, which seems to indicate a client-server problem rather than a caching problem.

I'm currently on v5.6.1.  Username is bilts if that helps in any way. Android 8.1.0

@veloce I'm also a developer with experience in both web and Android.  I'm not in a situation where I can commit a ton of time right now, but I can get my dev environment set up and help with inserting / reporting diagnostics if you can point me at useful areas in the codebase to log or alter.

**Comment by bilts** [comment] 2018-04-23 16:41
I should also mention that I've noticed glitchiness for a while, but when I first noticed this particular set of problems being an issue, I thought the website may have changed to not allow people to solve the same problem twice.  My hypothesis was that I was being shown repeats of problems I had solved before, so solving them wasn't affecting my score, so I wasn't able to get new problems.

That said, I should reiterate what I said in my initial report: This all works fine for me on the website.

**Comment by l3d00m** [comment] 2018-04-24 13:37
Ok, I could reproduce duplicated puzzles too. Same app version as above.

1. Play a puzzle or two
2. Stay in the puzzle screen when a new puzzle was loaded and you haven't played it
2. Exit the app from puzzle screen and force close it (Android makes it easier with Developer Options -> Don't keep apps in background)
3. Enter the app again and load puzzles
4. One of the first puzzles from step 1 is loaded again

I'm not sure if it can be always reproduced, I'll play around a bit further. This happenened while I had full internet connection

**Comment by bilts** [comment] 2018-04-24 18:46
I compiled the app and looked at network logs when logged in and have some more details here.  Surprisingly, I see the same issue running the app on my computer as I see when running on my phone.

First, my rating is 1443 as reported on the website and through the API, but 1492 in the app (don't want to hear it... it *had* been over 2000 and I got super lazy and stopped being able to see when it was tanking in the app)

Interestingly, the graphs on the website and in the app roughly agree and show that the 1443 number is from several games ago:

<img width="340" alt="screen shot 2018-04-24 at 1 56 46 pm" src="https://user-images.githubusercontent.com/61120/39206755-426094f2-47cc-11e8-973d-77dc1d2c9f6c.png">
<img width="246" alt="screen shot 2018-04-24 at 1 58 33 pm" src="https://user-images.githubusercontent.com/61120/39206763-47f7e5be-47cc-11e8-9c83-57afbb0faeda.png">
<img width="276" alt="screen shot 2018-04-24 at 2 31 27 pm" src="https://user-images.githubusercontent.com/61120/39206770-4d782f1c-47cc-11e8-9bfc-2ed1678cf973.png">

Here are relevant bits from loading a puzzle and playing it (pretty printed for sanity reasons):

https://lichess.org/training/65447/load

```json
{
  "game": {
    "id": "rF8uN7Js",
    "perf": {"icon": ")", "name": "Blitz"},
    "rated": true,
    "players": [
      {"userId": "piet1pegr", "name": "piet1pegr (2044)", "color": "white"},
      {"userId": "yonzon", "name": "yonzon (1799)", "color": "black"}
    ],
    "treeParts": {
      "ply": 30,
      "fen": "r4rk1/pp3ppp/1n6/2qp4/6b1/2PQ1N2/P3BPPP/R3R1K1 w - - 8 16",
      "id": "]A",
      "uci": "c8g4",
      "san": "Bg4"
    },
    "clock": "5+0"
  },
  "puzzle": {
    "id": 65447,
    "rating": 1366,
    "attempts": 20074,
    "fen": "r1b2rk1/pp3ppp/1n6/2qp4/8/2PQ1N2/P3BPPP/R3R1K1 b - - 7 15",
    "color": "white",
    "initialPly": 30,
    "gameId": "rF8uN7Js",
    "lines": {"f3g5": {"g7g6": {"e2g4": {"c5d6": "win"}}}},
    "vote": 74,
    "branch": {
      "ply": 31,
      "fen": "r4rk1/pp3ppp/1n6/2qp2N1/6b1/2PQ4/P3BPPP/R3R1K1 b - - 1 16",
      "id": "8I",
      "uci": "f3g5",
      "san": "Ng5",
      "children": [
        {
          "ply": 32,
          "fen": "r4rk1/pp3p1p/1n4p1/2qp2N1/6b1/2PQ4/P3BPPP/R3R1K1 w - - 0 17",
          "id": "YQ",
          "uci": "g7g6",
          "san": "g6",
          "children": [
            {
              "ply": 33,
              "fen": "r4rk1/pp3p1p/1n4p1/2qp2N1/6B1/2PQ4/P4PPP/R3R1K1 b - - 0 17",
              "id": "/A",
              "uci": "e2g4",
              "san": "Bxg4",
              "children": []
            }
          ]
        }
      ]
    },
    "enabled": true
  },
  "mode": "play",
  "user": {
    "rating": 1443,
    "recent": [
      [64880, -3, 1425],
      [64886, 12, 1422],
      [64889, 15, 1434],
      [64892, -6, 1449],
      [65011, 5, 1542],
      [65020, 12, 1547],
      [65024, -10, 1559],
      [65028, -8, 1549],
      [65031, 8, 1541],
      [65032, -8, 1549],
      [65033, 7, 1541],
      [65035, 12, 1548],
      [65038, -15, 1560],
      [65258, -6, 1510],
      [65259, -12, 1504]
    ]
  }
}
```

https://lichess.org/training/65447/round2

Request URL: https://lichess.org/training/65447/round2
Request Method: POST
Status Code: 200 OK
Remote Address: 37.187.205.99:443
Referrer Policy: no-referrer-when-downgrade

Body: `{"win":1}`

```json
{
  "user": {
    "rating": 1443,
    "recent": [
      [64880, -3, 1425],
      [64886, 12, 1422],
      [64889, 15, 1434],
      [64892, -6, 1449],
      [65011, 5, 1542],
      [65020, 12, 1547],
      [65024, -10, 1559],
      [65028, -8, 1549],
      [65031, 8, 1541],
      [65032, -8, 1549],
      [65033, 7, 1541],
      [65035, 12, 1548],
      [65038, -15, 1560],
      [65258, -6, 1510],
      [65259, -12, 1504]
    ]
  },
  "round": {"ratingDiff": 0, "win": true},
  "voted": null
}
```

Notice that it is registering the win, but awarding no points and thus isn't showing up in the score history.

It could very well be that I've played this particular puzzle before (I don't remember it) and the site is refusing to give points for replaying an app.  That would be a clean explanation, but I can't say for sure.  As I have said before, though, I've noticed a lot of duplicate puzzles appearing.

If the puzzles selected are directed by the server, it would seem that this is a lichess.org issue.

**Comment by poldie** [comment] 2018-04-25 06:54
What do you want in the way of reproduction steps? I pretty much only play puzzles on Lichess so this problem is 100% reproducable every day, for months.  Perhaps as a starting point add some logging to the app to dump my puzzle score/history there locally against what's on the server.

**Comment by l3d00m** [comment] 2018-04-30 16:09
Something new on my end: The duplicate puzzles happen on lichess' site as well. I finished this puzzle (https://lichess.org/training/68431) first in the app, then I got it again at lichess.com (after finishing rating + 0). 

I did a few other puzzles and exited lichess.com. After returning back I got the puzzle again, exactly what happened in the app too. So it might be a lichess web problem too. I'll open an issue there.

**Comment by l3d00m** [comment] 2018-05-04 06:47
As described in https://github.com/ornicar/lila/issues/4317, I could reproduce the other reported bug on lichess web as well. It seems like a generell lichess bug and not one only in the app.

**Comment by bilts** [comment] 2018-05-04 12:29
After dealing with it for over a month. I'm no longer seeing this in the app. Don't know what changed, maybe something server side.

**Comment by veloce** [comment] 2018-05-04 12:38
Something changed server side indeed. I also made a couple of small fixes app side. Closing this then.

**Closed by veloce** 2018-05-04 12:38 UTC

**Comment by natancox** [comment] 2018-09-09 17:28
Still is happening. Even after reinstall of Android app. This issue should be reopened.

**Comment by fwn** [comment] 2019-03-08 16:03
This issue should be reopened as it still persists in 6.1.1.

This bug can be completely avoided by using 5.3.1.

Bug can ONLY be reproduced if

* first the app version is greater 5.3.1
* and second batches of puzzles are solved on at least two clients alternately. (e.g.: The app and the web client or two apps on different devices.)

If clients are alternated - let's say first app (works!), then web (works!), then app (bug!) - puzzels get out of sync.

All puzzles played on the web will need to be replayed in the app without the account getting any rating for it.

Bug symptoms disappear after

* either replaying all previously solved puzzles in the app alone
* or clearing app data on the device.

We can provide documentation for this asynchronous puzzle behaviour as described if needed. We would love to provide any additional information to get this bug resolved, as it is an otherwise awesome, beautiful app!

**Comment by Emobe** [comment] 2019-07-18 14:22
This still happens...

**Comment by fmmarzoa** [comment] 2020-01-20 11:38
This is still happening.

If I remove the app data in Android, it will start showing new puzzles but as soon as I get back to the game after leaving, it'll start repeating the same old ones always from the same puzzle.

**Comment by gety9** [comment] 2020-01-25 22:32
Still happening on iOS. App version 6.3.0

**Comment by l3d00m** [comment] 2020-01-25 23:02
@veloce Could you reopen this? There are very regular reports about this on lichess forums too, see this search:

https://lichess.org/forum/search?text=puzzle+app

**Comment by vpatov** [comment] 2020-01-27 05:48
I am also experiencing the same issues described here. It has made the puzzles experience bad enough for me that I do them much less :(

**Comment by igroglaz** [comment] 2020-01-30 22:25
The same puzzles: https://lichess.org/training/61982 and https://lichess.org/training/61987

**Comment by feafarot** [comment] 2020-08-27 19:20
The issue is still present on the latest app
