### ISSUE TITLE
Buttons obscured at bottom of app

### ISSUE THREAD

**Issue by jerweb63** [veloce/lichobile#1942] opened 2021-12-04 10:33 UTC
Bug report: Controls at bottom of screen obscured by iOS swipe up handle. 

Phone hardware: iPhone 11 Pro

Phone operating system version: iOS 15.1

Version of lichess mobile beta: 7.14.0

Steps to reproduce:

After updating to iOS 15

Description of the observed behavior:

The controls at the bottom of the screen, flip board and analysis buttons, are covered by the swipe up handle of iOS. 

Description of the expected behavior:

The buttons should not be covered by the handle. Maybe the the row of buttons need raising?

![5B22947B-5DB3-4649-8E12-5C9A770328CF](https://user-images.githubusercontent.com/8494662/144706354-c707303a-accd-4c13-a644-a56d79dccaea.jpeg)

**Comment by jerweb63** [comment] 2021-12-04 11:12
Seems to have spontaneously cleared up.

**Comment by jas14** [comment] 2021-12-04 12:52
Duplicate of #1877

**Closed by jas14** 2021-12-04 12:52 UTC

**Comment by alectrocute** [comment] 2022-01-15 16:08
Not cleared up, still reproducing on iPhone 12 Pro Max.
