### ISSUE TITLE
App badge notification doesn’t update 

### ISSUE THREAD

**Issue by mozltovcoktail** [veloce/lichobile#1453] opened 2020-12-22 18:30 UTC
On iOS, the notification badge on the app icon letting you know you know it’s your move doesn’t update once you’ve opened the app and played a move. The workaround is to open the app, play the move, force-close the app, then reopen it. After this, this badge will update.

**Comment by atomoton** [comment] 2021-01-19 15:36
duplicate of https://github.com/veloce/lichobile/issues/1228

**Closed** 2021-01-24 17:07 UTC
