### ISSUE TITLE
End of game controls UX issue on iPhone 12

### ISSUE THREAD

**Issue by amirz-sb** [veloce/lichobile#1950] opened 2021-12-12 13:44 UTC
The controls at the end of a game are all the way at the bottom of the screen, and very small, making it hard to click since the OS app control line (the white line at the bottom) share the same place on the screen.
Please enlarge them and also move them higher up.
This capture is from an iPhone 12 Pro.

![FC8A36AD-4455-48ED-B365-AD02D363575F](https://user-images.githubusercontent.com/25924273/145714600-78b3cf9f-bd07-45c6-853c-406732e413f5.png)

**Comment by jas14** [comment] 2021-12-13 23:00
Duplicate of #1877 - please give that issue a thumbs-up to indicate you are affected. Thanks!

**Closed by jas14** 2021-12-13 23:00 UTC
