### ISSUE TITLE
Scan chess positions with camera

### ISSUE THREAD

**Issue by a-waider** [veloce/lichobile#1845] opened 2021-09-14 15:51 UTC
**Is your feature request related to a problem? Please describe.**
Always when I see a non lichess chess game without an engine nor a FEN and want to use the lichess engine/analysis I need to setup the board myself. For complex positions it can take some time. E.g. you watch a chess video in YouTube and want to analyse it. There is no way to quickly get the position.

**Describe the solution you'd like**
I'd like to have a function to scan an chess position with my phone's camera from the monitor. The app then outputs the FEN and a button to jump right into the analysis with engine support.

**Describe alternatives you've considered**
There are apps that can kind of do this. [Example](https://play.google.com/store/apps/details?id=com.fimetech.chessfimee)
But this app's engine is just garbage.
Not analysing at all is not a considerable solution.

**Additional context**
_Empty_

**Comment by jas14** [comment] 2021-09-14 16:51
Duplicate of #561

**Closed by jas14** 2021-09-14 16:51 UTC
