### ISSUE TITLE
Dark mode launch screen

### ISSUE THREAD

**Issue by DaniSpringer** [veloce/lichobile#1623] opened 2021-03-24 08:46 UTC
Please make the iOS app LaunchScreen.storyboard dark in dark mode

**Comment by DaniSpringer** [comment] 2021-05-23 23:03
Anybody here?

**Comment by jas14** [comment] 2021-05-24 13:35
@DaniSpringer thanks for your feedback - I'm going to close this issue as a duplicate of #1366. Please give that issue a thumbs-up so everyone can gauge interest over there. 👍

**Closed by jas14** 2021-05-24 13:35 UTC
