### ISSUE TITLE
Chess puzzle problem with new latest update

### ISSUE THREAD

**Issue by Milt33** [veloce/lichobile#1039] opened 2019-09-23 12:14 UTC
Bug
Before latest update the chess puzzles werr ok.The same for years grading system
But know things changed
Suddenly it was yesterday at Sunday 22 Sep 2019 the puzzles were only 20 30 and they were repeated continiously.I mean after their completion they were repeating again.The grade system changed the puzzles were giving grades about 1700-1900 only.(I was 2400 in puzzles that time)
Whats going on?
Have you changed the system of  grading?
Plus the puzzles are seemed to have been played for 300-500 thousands people every time when right before your changed the number was about 1-10 thousand

**Comment by vpatov** [comment] 2019-09-27 18:04
Unfortunately your description is somewhat hard to understand. The clearer you make your description, the more likely you are to get helpful feedback.

One potential workaround you can try in the meantime is clearing your app cache, which can either be done through the settings on your phone, or by reinstalling the app. This might resolve your issue, if it was caused by an inconsistency between your phone's app data and the server data.

**Comment by Milt33** [comment] 2019-09-27 18:14
Lets say it again
I have solved almost 29.000 puzzles.A huge amount.
When this happened you installed also the new version of the app.
The problem was that the puzzles stopped to changing and were showed up by
then only 30-40.(i played them at least five times each).
I re installed the app 2 times but nothig happened.Then i opened the
lichess.org from desktop and i saw that i start receiving again new
puzzles.But the situation in the phone app was remained the same.
I wondering if this was a problem because i solved so many puzzles or its
an issue related with your new update.
With regards

Στις Παρ, 27 Σεπ 2019, 21:04 ο χρήστης Vasia Patov <notifications@github.com>
έγραψε:

**Comment by l3d00m** [comment] 2020-01-25 23:05
Sounds similiar to #813

**Comment by veloce** [comment] 2021-09-16 10:45
Fixed by new puzzles api.

**Closed by veloce** 2021-09-16 10:45 UTC
