### ISSUE TITLE
Visual bug - my king got into check from checkmating a friend

### ISSUE THREAD

**Issue by eyal282** [veloce/lichobile#1767] opened 2021-07-13 09:29 UTC
**Describe the bug**
My king is shown in check AFTER I checkmated my opponent.

**To Reproduce**
Pressing the friend list, then the sword icon, then 10+5 game with random side.

**Expected behavior**
The checkmated king is red, rather than the checkmating king.

**Screenshots**
https://lichess.org/4AGEIsuJ/white#62
![Screenshot_20210713-122107_lichess](https://user-images.githubusercontent.com/39803639/125427988-12fdffdc-0a6b-456f-9ca0-61e4dbcc6d19.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android A12]
 - OS: [No clue]
 - Browser [Just the app]
 - Version [No clue]

**Additional context**

**Comment by jas14** [comment] 2021-07-13 11:04
Duplicate of #1012

**Closed by jas14** 2021-07-13 11:04 UTC
