### ISSUE TITLE
Bug - new version does track finger touch correctly (iOS)

### ISSUE THREAD

**Issue by ChristianWatkins** [veloce/lichobile#1059] opened 2019-10-03 13:42 UTC
**bug report**

**Current behavior:**
The place I touch the screen during game play is record as a slightly different position by the app.
While I can't be sure it is not due to a hardware error, I don't experience the same kind of error in other chess apps.
I need to touch the screen a bit lower than expected.

**Environment information**
Apple iPhone Xs Max
iOS 12.4.1
Newest lichess version

- phone hardware
- phone operating system version
- version of lichess mobile

**Comment by Calinou** [comment] 2019-10-03 13:56
I wonder if the cause is similar to https://github.com/godotengine/godot/issues/31503.

**Comment by veloce** [comment] 2019-10-05 12:02
@ChristianWatkins can you try to disable move list (from settings game behavior menu), and see if the problem persists? thanks

**Comment by ChristianWatkins** [comment] 2019-10-06 20:48
I just saw that I was in zen mode. So that might be something to check.
I disabled zen mode now + disabled move list nad playing seems to be ok
again.

**Comment by veloce** [comment] 2019-10-07 14:58
ok thanks for the info, will check zen mode.

**Comment by Jidbo** [comment] 2019-10-17 22:19
I have the same problem when zen mode is enabled. When disabled the problem seems to disappear even though my move list is still enabled. I'm on iPhone X, iOS 13.1.3 and Lichess version 6.3.0.

**Comment by niklasf** [comment] 2019-11-12 11:55
This issue was reported to also happen unconditionally on Huawei Honor 10 with Android 9:
https://lichess.org/forum/lichess-feedback/app-registers-input-to-high

**Comment by Syoc** [comment] 2020-02-13 08:45
I also have this issue. I seems to be due to zen mode. Lichess v7.0.0, iPhone Xr.

**Comment by Baikalcadillac** [comment] 2021-12-30 16:09
Finally I don't have any issues with zen mode, anyone else?

**Comment by veloce** [comment] 2021-12-31 09:52
Closing the issue as it was fixed in 7.14.1

**Closed by veloce** 2021-12-31 09:52 UTC
Labels: bug
