### ISSUE TITLE
Huawei bug

### ISSUE THREAD

**Issue by saeid8036** [veloce/lichobile#1812] opened 2021-08-20 18:15 UTC
Hi. I use Android app in Huawei Nova 7i.
When opening the app, 
"Your rendering engine is old, you must update your Huawei WebView to latest version"
But my WebView is the last version.
And the fist page (choosing time of games) doesn't appear .So what's the problem?
Model: Nova 7i_ google has installed manually
OS: Android 10
Lichess V. 7.11.3
![Screenshot_20210820_194145_org lichess mobileapp](https://user-images.githubusercontent.com/80723385/130276443-966180e5-8b75-4317-9344-1113ac661bbf.jpg)

**Comment by jas14** [comment] 2021-08-21 11:08
Duplicate of #1448.

**Closed by jas14** 2021-08-21 11:08 UTC

**Comment by saeid8036** [comment] 2021-08-21 14:16
> Duplicate of #1448.

But no real good answer for that have been made

**Comment by jas14** [comment] 2021-08-21 14:21
Yes unfortunately not because we can't reproduce the issue... https://github.com/veloce/lichobile/issues/1448#issuecomment-803276866

**Comment by saeid8036** [comment] 2021-08-21 16:31
So, this issue remains forever...
{<>}!

**Comment by jas14** [comment] 2021-08-21 21:44
Yes, this is a free and open-source project maintained by volunteers. If you can find someone who wants to contribute and owns a Huawei phone that has the issue, please send them our way.

**Comment by startnoob** [comment] 2022-10-30 10:12
Hey, I just looked through the code in ```MainActivity.java``` and I figured out what the problem is:
``` java
private PackageInfo getCurrentWebViewPackageInfo() {
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        /* Starting with Android O (API 26) they added a new method specific for this */
        return WebView.getCurrentWebViewPackage();
      } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        /*
         * With Android Lollipop (API 21) they started to update the WebView
         * as a separate APK with the PlayStore and they added the
         * getLoadedPackageInfo() method to the WebViewFactory class and this
         * should handle the Android 7.0 behaviour changes too.
         */
        Class webViewFactory = Class.forName("android.webkit.WebViewFactory");
        Method method = webViewFactory.getMethod("getLoadedPackageInfo");
        return (PackageInfo) method.invoke(null);
      } else {
        /* Before Lollipop the WebView was bundled with the OS. */
        try {
          return this.getPackageManager().getPackageInfo("com.google.android.webview", 0);
        } catch (PackageManager.NameNotFoundException e) {
          Log.e(LOGTAG, "Cannot find package info: " + e.getMessage());
        }
      }
      return null;
    } catch (Exception e) {
      Log.e(LOGTAG, "Cannot determine current WebView engine. (" + e.getMessage() + ")");
      return null;
    }
  }
```
It just check whether ```com.google.android.webview``` exists and updated, However, Huawei's Webview is seperate from goole's. Huawei uses ```com.huawei.webview``` instead. Currently its version is 11.1.5.315 on my Huawei Mate 20 phone up to 2022.10.30. I don't write java and unable to make a PR directly, but hope someone could change this line:```return this.getPackageManager().getPackageInfo("com.google.android.webview", 0);```
It's quite annoying to close the window when I open lichess, hope problem fixed soon.
