### ISSUE TITLE
Place overlay action buttons closer to the right of the display

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#70] opened 2015-01-27 18:10 UTC
In extension, put the icons on the right of the display ("Propose a takeback, Offer draw, Resign"). As most people are right handed.

**Comment by veloce** [comment] 2015-01-27 20:12
All of the buttons, including text, is clickable, even if it's not obvious. So to me the issue is more one of design.

**Comment by veloce** [comment] 2015-02-02 21:39
Won't fix for now

**Closed by veloce** 2015-02-02 21:39 UTC
