### ISSUE TITLE
Add haptics on iOS

### ISSUE THREAD

**Issue by FaroukZeino** [veloce/lichobile#1394] opened 2020-10-03 21:19 UTC
Please add support for haptics when making a move on iOS.

**Comment by FaroukZeino** [comment] 2020-11-24 21:54
Any update? the old vibration is very bad!

**Comment by gregorp** [comment] 2022-01-13 13:46
This is a duplicate of #1918, which has a few comments. I'd suggest closing the issue here and focusing attention there.

**Closed** 2022-01-13 13:55 UTC
