### ISSUE TITLE
UI bug on chess pieces

### ISSUE THREAD

**Issue by Chryslr** [veloce/lichobile#1915] opened 2021-11-14 09:26 UTC
When I play matches, the pieces aren't looking properly and some are even invisible. The pieces still work properly but it's extremely hard to play if you can't really see the pieces.

**To Reproduce**
1. Go to any match like rapid or puzzles 
2. See error

**Screenshots**
![Screenshot_2021-11-06-22-27-20-88](https://user-images.githubusercontent.com/92014588/141675302-229b77b3-a149-46a7-9b7f-5849f87630b3.jpg)

**Smartphone (please complete the following information):**
 - Device: [Oppo A5s]
 - OS: [ColorOS V5.2.1]
 - Browser [Mobile app]
 - Version [7.13.1]

**Additional context**
This bug also happened on the website

**Comment by Chryslr** [comment] 2021-11-14 09:39
Turns out, I'm not alone

**Comment by jas14** [comment] 2021-11-14 13:30
Duplicate of #1865

**Closed by jas14** 2021-11-14 13:30 UTC
