### ISSUE TITLE
reproducible irresponsiveness

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#50] opened 2015-01-15 15:13 UTC
- open a game with > 20 moves
- hit the back button 20 times very fast
- App stops responding to any input.

Galaxy SII, Android 4.4.4

**Comment by veloce** [comment] 2015-01-17 12:21
Can't reproduce on a nexus 5. But experience lag when hitting back button very fast

**Comment by ornicar** [comment] 2015-01-17 12:23
OK we'll debug it on my SII next week

**Comment by daamien** [comment] 2015-01-21 10:33
Same bug here although I can't reproduce it every time.

* open  a 5+0 game
* hit back button several times and went to the first move
* hit forward button several times to go the last move
* can't make a new move even though it's my turn to play. 
* every square I touched turned blue and stayed blue.

Galaxy SII, Android 4.1.2

here's one game where it happened : http://fr.lichess.org/Nn6bQ2qKa0Yg

**Comment by clarkerubber** [comment] 2015-01-26 11:31
I've come across new unresponsiveness issues that seem to be new in 1.0.15. This makes the app practically unusable.

Steps to reproduce: 
1. Open the application for the first time.
2. Open up the side menu.
3. Any swipe or touch is interpreted as "new OTB game"

Result: New OTB game started.
Expected result: The side menu to be scrollable and actionable.
Device: HTC Incredible S
OS: Android 4.4.4 w/ Cyanogen mod 11-20140919-UNOFFICIAL-vivo

**Comment by veloce** [comment] 2015-02-03 18:56
Closing this. We'll reopen a new issue when finding new unresponsivenesses.

**Closed by veloce** 2015-02-03 18:56 UTC
Labels: bug
