### ISSUE TITLE
Lobby feature in mobile application - View and join open lobbies in the mobile app.

### ISSUE THREAD

**Issue by axydavid** [veloce/lichobile#1672] opened 2021-05-07 06:37 UTC
**Is your feature request related to a problem? Please describe.**
There is a significant voice on the internet frustrated with the fact that we can't access the lobby tab when we use the lichess app.
The mobile market already represents the majority of the internet users, and this is especially true in developing countries where users can't typically afford to own a PC/laptop but a cheap android phone, and let's not mention their significantly smaller data allocation.

Here are a few links of people requesting this feature:
https://www.reddit.com/r/chess/comments/7kzsl7/no_lobby_in_lichess_android_app/
https://lichess.org/forum/lichess-feedback/lobby-on-android
https://lichess.org/forum/lichess-feedback/viewing-lobby-challenges-in-the-mobile-app
https://lichess.org/forum/lichess-feedback/why-theres-no-lobby-in-mobile-app

Have a look at the apple appstore reviews:
![image](https://user-images.githubusercontent.com/11884779/117407840-b3d8d880-af41-11eb-824c-ef55fd2e7fbe.png)

A simple google search will reveal many people frustrated with the lack of this feature:
![image](https://user-images.githubusercontent.com/11884779/117407229-d74f5380-af40-11eb-9c50-e4f3d54ffb24.png)

**Describe the solution you'd like**
Provide a way for the mobile app users to be able to see and join open lobbies.

**Describe alternatives you've considered**
Just put the lobby tab as it's implemented on the website already. Or provide a way for us to see available lobbies while searching for a game.

**Additional context**
It will improve the user experience as usually when we search for any game specifically a custom game we're not so strict with the specific time and starting side as long as it's the game mode we want. This will enable us to be able to find an opponent faster and spend less time waiting to be paired with one. It will especially help people that are playing a less popular game mode.

**Comment by jas14** [comment] 2021-12-07 13:12
I'm closing this as a duplicate of #1149 , as that issue was submitted first. Please do give that issue a thumbs up so we can gauge interest for this request in one place. Thanks!

**Closed by jas14** 2021-12-07 13:12 UTC
