### ISSUE TITLE
Use tap-like haptics rather than full-on vibrate for game events.

### ISSUE THREAD

**Issue by MiguelGuthridge** [veloce/lichobile#1966] opened 2022-01-03 21:27 UTC
**Is your feature request related to a problem? Please describe.**
I really like the idea of having my phone give me tactile feedback when an event happens in the game, but I feel like the existing vibration is too strong and loud on most phones, which can distract from the game.

**Describe the solution you'd like**
It'd be nice to use a tap-like haptic event rather than a vibrate event, to make the feedback more subtle and less distracting.

**Describe alternatives you've considered**
If not all users want a "quieter" tactile event, a slider could be used to control the strength of the vibration.

**Comment by jas14** [comment] 2022-01-03 23:18
Thanks for the detailed request - I'm closing this as a duplicate of #1918. Please give that issue a thumbs up so we can keep an eye on demand for that feature

**Closed by jas14** 2022-01-03 23:18 UTC

**Comment by MiguelGuthridge** [comment] 2022-01-04 01:06
Hopefully it'd work on Android too - sorry I didn't see the duplicate when I searched
