### ISSUE TITLE
Inbox shows unread messages, but there aren't any

### ISSUE THREAD

**Issue by xmgr** [veloce/lichobile#1278] opened 2020-06-08 22:32 UTC
**Describe the bug**
In the App on the left side under the Account section it says "Inbox (1)" but there are no unread messages actually.

**To Reproduce**
1. Go to User Menu
2. Click on it
3. Inbox
4. There it is

**Expected behavior**
The "(1)" should not be there.

**Screenshots**
![Screenshot_20200609-003144_lichess](https://user-images.githubusercontent.com/20494561/84086652-a9882480-a9e8-11ea-8693-d393bd923909.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android Version 10
 - Browser: none (App Version)

**Additional context**
Lichess username: marius_gerum

**Comment by thetasquared** [comment] 2021-03-26 14:20
I have the same issue. Both on my Pixel 2 and an old tablet.  Mine shows inbox (2) no matter what I do. Today I deleted all my inbox messages, deleted all app data, uninstall and re-installed. Did not fix the issue.

**Comment by jas14** [comment] 2021-03-29 22:54
I can also repro this. It looks like we get our unread messages count [directly from the server](https://github.com/ornicar/lila/blob/970287a2f06d90d5b032ca1962387369d0e06ebe/modules/msg/src/main/MsgCompat.scala#L57-L72), so this may be a server-side caching or calculation issue.

**Comment by jas14** [comment] 2021-04-01 15:04
https://github.com/ornicar/lila/pull/8505 was deployed today and I can no longer reproduce the issue. @xmgr , @thetasquared , please confirm the fix and we'll close this issue

**Comment by thetasquared** [comment] 2021-04-01 15:14
> [ornicar/lila#8505](https://github.com/ornicar/lila/pull/8505) was deployed today and I can no longer reproduce the issue. @xmgr , @thetasquared , please confirm the fix and we'll close this issue

FIXED!   Thank you.

**Closed** 2021-04-02 08:42 UTC
