### ISSUE TITLE
Study makes the app crash on android

### ISSUE THREAD

**Issue by ananas-dev** [veloce/lichobile#1836] opened 2021-09-05 12:24 UTC
**Describe the bug**
https://lichess.org/study/kI8ikTU4 makes the app crash after a few seconds.

**To Reproduce**
1. Open the study
2. Don't touch anything and wait a few secs

**Video**
https://user-images.githubusercontent.com/46646129/132126602-3dc8387c-f8be-4c4e-931c-f4bce743ff8d.mp4

**Smartphone:**
 - Device: OnePlus 5t
 - OS: Android 11 (LineageOs 18.1)
 - Lichess Version 7.11.3

**Comment by jas14** [comment] 2021-09-05 12:25
Duplicate of #1725, fixed by #1832

**Closed by jas14** 2021-09-05 12:25 UTC
