### ISSUE TITLE
Over the board clock.

### ISSUE THREAD

**Issue by Xuprooshon** [veloce/lichobile#1487] opened 2021-01-09 15:02 UTC
**Describe the bug**
When playing timed over the board with a friend in the same device, th clock goes insane

**To Reproduce**
1. Go to 'over the board'
2. Start playing a game with sudden death clock
3. Notice that after the first move the clock is completely in chaos
4. Also, the clock starts ticking after white's move wich is not fair for black.

**Expected behavior**
The clock should start after blacks move without getting insane.

**Screenshots** 
![Screenshot_20210109-155810](https://user-images.githubusercontent.com/77200716/104094899-1079fe80-5294-11eb-9bbb-33206ea44305.png)

**Smartphone (please complete the following information):**
 - Device: itel P36
 - OS: Android 9
 - Browser Opera
 - Version 7.6.1

**Comment by jas14** [comment] 2021-01-11 15:20
Duplicate of #1472.

**Closed** 2021-02-27 11:02 UTC
