### ISSUE TITLE
Over the Board is not working

### ISSUE THREAD

**Issue by gkts** [veloce/lichobile#1387] opened 2020-09-25 08:48 UTC
**Describe the bug**
“Over the Board” isn’t working at Lichess mobile in iOS

**To Reproduce**
1. Go to Lichess mobile 
2. Click on Over the Board
3. See error

**Expected behavior**
I would like to play over the board on Lichess with anyone

**Screenshots**
![2F2FBFA3-0028-4AEE-AB61-E6E2615808F6](https://user-images.githubusercontent.com/63871763/94246336-4a610800-ff24-11ea-8572-868773eb0be6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14
 - Lichess version 7.5.0

**Comment by freefal** [comment] 2020-09-30 13:57
I can't reproduce this. Are you still experiencing this issue after closing and reopening the app?

**Closed** 2020-10-14 18:31 UTC
