### ISSUE TITLE
Menu buttons become unresponsive

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#38] opened 2015-01-13 22:57 UTC
Steps to reproduce: Use application a bit by moving back and forwards between menus, sliding the current games tiles, etc...

Device: HTC Incredible S
OS: Android 4.4.4 w/ Cyanogen mod 11-20140919-UNOFFICIAL-vivo

**Comment by veloce** [comment] 2015-01-14 09:19
Since it's hard to reproduce, we need #35 first to identify this

**Comment by ornicar** [comment] 2015-01-14 10:37
yeah, happens to me too, when switching between correspondence games

**Comment by veloce** [comment] 2015-02-06 19:05
Closing since we can't reproduce anymore for sure.

**Closed by veloce** 2015-02-06 19:05 UTC
Labels: bug

**Comment by ornicar** [comment] 2015-02-07 14:02
I'm not seeing it anymore.
