### ISSUE TITLE
Berserk option gone in iOS / Android

### ISSUE THREAD

**Issue by jamespherman** [veloce/lichobile#1164] opened 2020-03-24 15:06 UTC
Not sure why my issue was closed?! This is still happening. No berserk option in Android (LG v40; latest version of app) or iOS (iPad mini 5th gen; latest version of app).

**Comment by niklasf** [comment] 2020-03-24 15:08
The issue is fixed in the codebase, but the server has not yet been updated. This will happen in the next couple of days.

**Comment by jamespherman** [comment] 2020-03-24 15:11
Thanks so much for letting me know and for working on this fantastic app! A comment: wouldn't it make sense for whomever closed my issue to have said this rather than just closing it and assuming I'd figure it out by other means? Just saying, this way seems like more work for everybody...

**Comment by niklasf** [comment] 2020-03-24 15:18
They did:
![](https://user-images.githubusercontent.com/402777/77442776-ed588e00-6dea-11ea-836e-2bf686868f5f.png)

"Closed in xyz" means it was automatically closed because change xyz fixes the bug.

**Closed** 2020-03-24 18:57 UTC

**Comment by jamespherman** [comment] 2020-03-24 19:17
> They did:
> ![](https://user-images.githubusercontent.com/402777/77442776-ed588e00-6dea-11ea-836e-2bf686868f5f.png)
> 
> "Closed in xyz" means it was automatically closed because change xyz fixes the bug.

Thanks so much for the explanation and I'm sorry that my own ignorance caused extra nonsense.
