### ISSUE TITLE
Analysis no longer works on iOS 10

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#429] opened 2016-09-22 16:54 UTC
I'm experiencing this new behavior since updating to iOS 10 (I updated from 9.3.5 to 10.0.1, iPhone 6). Analysis mode after solving a Training puzzle does not work at all (see screenshot): 

- the game history is blank
- computer analysis is not there
- the move forward/backward buttons don't function
- (the other buttons do work, except Opening Explorer can't find any openings/games)

Analysis mode does *mostly* work in other modes (over-the-board, etc): the game history is displayed, and move buttons work, but the analysis doesn't generate results (it just displays ⏳, never displaying any score or move recommendation).

![2016-09-20 at 21-58-36](https://cloud.githubusercontent.com/assets/6884276/18757595/26eaac24-80ba-11e6-9673-8c99a1b43084.jpg)

**Comment by veloce** [comment] 2016-09-27 19:26
Closing since I can't reproduce on iOS10 with current version

**Closed by veloce** 2016-09-27 19:26 UTC

**Comment by quinncomendant** [comment] 2016-09-29 20:56
BTW, I uninstalled Lichess, and reinstalled. I'm still having this problem.
