### ISSUE TITLE
Searching for a game on mobile is possibly broken

### ISSUE THREAD

**Issue by mekhami** [veloce/lichobile#410] opened 2016-08-30 22:40 UTC
When I search for a game on mobile, often I'll wait ages and nothing will happen. If I do join the game, it's almost always aborted when I enter.

I started a search on the mobile app, then looked on the desktop at the open games and where I would usually see my own seek, it's not listed there.

Not sure what other information I can give you other than I'm using a Samsung Galaxy Tab S2 using the most updated version of the app and OS.

**Comment by veloce** [comment] 2016-09-19 08:17
Are you sure you are not using filter that prevent you seeing the game? 

Do you use a time setup not common (the most probable explanation if you have to wait long)

**Comment by veloce** [comment] 2016-10-26 06:55
Closing since I can't reproduce

**Closed by veloce** 2016-10-26 06:55 UTC
