### ISSUE TITLE
Mobile App- My two main complaints

### ISSUE THREAD

**Issue by MyQueenGetsAround** [veloce/lichobile#615] opened 2017-06-20 03:10 UTC
I've started to use Lichess recently but find the mobile app to be terrible. I have two major complaints with it which makes playing with it pretty bad. I am writing this post because I want them to correct it so that I can use Lichess as my main chess app (I'm a diamond Chess.com member but am looking to move away from the site).

1. The app is not responsive enough to touch. It misses a lot of my gestures. Playing lightning on it would be near impossible. I can be up a piece but down to 30 seconds. On the chess.com app I'd have no problem converting it into a win. Lichess it misses so many gestures and is so unresponsive that I often will lose the position on time.

2. Everytime I premove I get an orange message telling me how to undue it. This is super annoying and almost reason enough not to use the app. Premoves are done often in blitz for recaptures, forced moves or low on time. I don't need to see an orange message every second move pop up on my phone. I mean, I'm not new.  Give the option to turn it off.

**Comment by ornicar** [comment] 2017-06-20 07:06
The premove message was already removed on the site; it could be removed from the app as well.

**Comment by veloce** [comment] 2017-06-20 07:58
piece drag'n drop should be very responsive, there has been a lot of work done on that specific part ;

what phone do you have?, what do you mean exactly be missing a lot of gestures?

**Comment by veloce** [comment] 2017-06-20 07:59
TODO:

- [ ] remove premove message

**Comment by MyQueenGetsAround** [comment] 2017-06-20 15:59
I have a Galaxy S5.  The way I play on a phone is I tap the piece I am likely to move( usually on my opponent's turn).  Then I hover over the square I want to move it to ready to tap it or move another piece.  When my time is low I am rapidly tapping the piece I want to move and then the destination square.  I don't drag.  What I find is the app doesn't always register the taps.  Chess.com does on the same phone and I don't have any unintended behavior with it.

When using the chess.com app I feel I am on an almost equal playing field to someone on a desktop with a mouse.  On Lichess, the misreads cost seconds and when you only have 30 seconds left, that is game.  I feel playing bullet on it would be impossible.

This is just my user feedback as someone who'd prefer to use Lichess than a commercial app.  Glad to hear the premove warning will be removed.

**Comment by veloce** [comment] 2017-06-20 16:56
I think the drag and drop is indeed more optimized and some people are playing fast games and have no complaint. Maybe it's easier to play with drag and drop on a touchscreen device, but I don't want to penalize people who do want to play with tap only. 

I'll try to play fast games and using tap only to test the feeling.

If I understand you correctly, the problem is tap misreads that cost you time. I really don't know if it's possible to improve tap recognition but I'll try. Maybe this is due to the tap and drag mixed and provide an option to disable drag would help.

**Comment by MyQueenGetsAround** [comment] 2017-06-20 17:12
I don't drag because my big fingers make it too hard to see the board.  On
a small screen phone you will probably get that a lot.  The faster you move
the more likely it is to not register a tap.

**Comment by veloce** [comment] 2018-03-25 19:49
Closing this in favor of #528 . When the latter is implemented it will probably help with this issue.

**Closed by veloce** 2018-03-25 19:49 UTC
