### ISSUE TITLE
Resign message remain on center after rematch until next app relaunch

### ISSUE THREAD

**Issue by hot-happy** [veloce/lichobile#1757] opened 2021-07-04 19:36 UTC
After opponent resign & rematch request, resign or rematch message remain in center of display until relaunch app.

In IOS app I play bullet (1 min) game in anonymous mode.
When my opponent resign and rematch very fast (resign and immediately send rematch request)
Resign  message (or sometimes rematch message) remain at the center of display and won't hide. (until next app relaunch)

**Expected behavior**
Resign message always should hide after a few seconds.

**Smartphone (please complete the following information):**
 - Device: [iPhone 5s]
 - OS: [iOS 12.5.1]
 - Browser [Lichess IOS application]
 - Version [7.11.3]

Thank you and sorry for my English weakness ;)

**Comment by jas14** [comment] 2021-07-04 19:56
Duplicate of #1481

**Closed by jas14** 2021-07-04 19:56 UTC
