### ISSUE TITLE
Some bugs found in Android version

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#472] opened 2016-10-28 14:05 UTC
1. Puzzle solution sound (Bug)
   There is no piece moving sound when viewing the correct puzzle solution by clicking the forward arrow (double right arrow).
2. Premove appeard in Analysis board (Bug)
   Sometimes in analysis board, one side has made a move while the computer still considers this side has not  moved. So the move from other side seems a "Premove".
   For instance, when I was playing the analysis board, I made a move as white. But the computer still considered white has not moved. And if now I tried to move black pieces, it will appear as a premove which should not appear in the analysis mode. At the same time, the board is actually freezed, no side can move. White is already moved though the computer thinks not. Black may try to move but it is considered as a premove. This situation can happen for black.
   One solution is to go back one move by clicking the backward arrow, and wait a few seconds, then doing exactly the same move actually won't cause any problem this time.
   I don't know how to reproduce this bug since I really didn't find a pattern. But it happens in a high frequency.
3. No Caro-Kann Defense: Steinitz Variation in Board Editor (Bug)
   There is no Caro-Kann Defense: Steinitz Variation (a predefined starting position) in Board Editor. If I choose this variation, it will directly jump to the previous variation which is Caro-Kann Defense: Panov-Botvinnik Attack.
4. Anaysis doesn't start immediately when going into Analysis board (Bug)
   When I get into the analysis board from a game or a board editor, the analysis doesn't start immediately even which side moves first is already decided. I have to make a tentative move then the analysis will start.
5. Trying to go back when in choosing variant interface from "continue from here" (Bug)
   If I try to start a offline game (continue from here) from analysis board or board editor, and then if I click back button instead of "Play" button in the middle when in "choosing the variant" interface, the screen will freeze instead of go back to the previous board editor or analysis board.
6. Changing variant in Analysis board (Feature Request)
   Can we be allowed to change chess variant when in Anlaysis board? Currently, there is no way to do variant analysis directly from the anlaysis board. And if I want to do a variant analysis I have to start a new variant game then click the analysis button in the new game. But it is very inconvenient.
7. End game positions in board editor (Feature Request)
   Can we have some end game positions in addition to the current starting positions in board eidtor? It would really help to improve.

Thanks!

**Comment by veloce** [comment] 2016-10-29 11:08
Thank you very much for this detailed bug report!

Here's the list of bugs to track resolution:

- [ ] bug 1
- [ ] bug 2
- [ ] bug 3 
- [ ] bug 4
- [ ] bug 5

**Comment by sepiropht** [comment] 2016-11-02 00:06
I made a pr for the bug 3, but there is the same issue in the web app, i suppose they share the same json.

I think i can also add some endgames positions if it useful.

**Comment by JuicyRyan** [comment] 2016-11-02 01:17
Thank you for your reply! Some end positions would be great! Also, I don't know whether you guys can reproduce all bugs mentioned above. So don't hesitate to tell me if a bug can't be reproduced. For me, those bugs are real. The second bug of offline analysis is really annoying.

**Comment by veloce** [comment] 2016-11-02 09:02
@sepiropht about bug 3, the json was copied, so the same PR should be done in ornicar/lila repo.

If endgame positions are useful I'll certainly accept a PR, my only concern is that the positions list may be too long with both opening & endgame positions.

**Comment by sepiropht** [comment] 2016-11-02 09:26
Yes thanks!  You accept my first pr to open source.

I will see if can set up the web app and do the same pr.

May be we can do another select for endgame and specify the first 'opening' and the second 'endgame' ?

**Comment by veloce** [comment] 2016-11-03 09:18
Maybe yes, I don't see what else to do. Keep the 'clear board' in both and the standard setup only in openings I guess

**Comment by veloce** [comment] 2016-11-06 09:43
@JuicyRyan about bug #2 I can't reproduce a blocking issue hère.

I do find that black moves are premoves sometimes when you are moving quickly enough, but this is not an issue since the premove results as a

**Comment by veloce** [comment] 2016-11-06 09:47
... Typing the comment from my phone is not easy... So the premove ends up in a move and i'm not able to get a situation where the board is freezed. If you do have steps to get to a freezing board situation please post them here. Otherwise i consider this is a non blocking minor issue

**Comment by JuicyRyan** [comment] 2016-11-06 15:53
![screenshot_20161106-083620](https://cloud.githubusercontent.com/assets/12246221/20039136/51c39270-a3fc-11e6-992d-ebf398d6862a.png)
(Premove in Analysis Board)

Currently, I don't have a specific way to exactly produce bug 2. But it seems if I move a piece on board quicily, quickly enough that the record doesn't have enough time to record it, then this bug tends to occur. Although I can't find a exact way to reproduce this bug, I really don't think this is a minor issue. This bug happens way too often and it is really annoying. And this bug didn't exist back in 4.42. (I didn't experience any update during 4.42 and 4.7.0 so I don't know whether such problem exists.) And by "freeze" I don't mean you can't do anything. I only mean that no side is able to make next move when this occurs. But I can still solve it manually by going back one move and do the exact same move a little bit slowly. I really hope this bug can be fixed. 

Thanks! Merci!

**Comment by veloce** [comment] 2016-11-07 21:30
Well I simply disabled premoves in analysis board. Hope that will solve your issue.

**Comment by veloce** [comment] 2016-11-09 12:51
All bug fixed, closing.

**Closed by veloce** 2016-11-09 12:51 UTC
Labels: bug
