### ISSUE TITLE
Count down should be on a left hand side by default.

### ISSUE THREAD

**Issue by wsobasik** [veloce/lichobile#1084] opened 2019-11-18 20:41 UTC
#Feature request

When playing (especially bullet) thumb finger hides the count down timer. To check how much time you have left you need to move your finger away all the time while playing- which is annoying.

Best it that would be configurable OR as most users is right handed on the left hand side.

**Comment by madivad** [comment] 2021-02-02 11:11
Hi, I've come to say the same thing, being right handed and using an ipad or iphone, my hand sits over the timer and I have ran out of time a couple of times now as I was totally oblivious as to home much time I had left. I'm surprised this is so old a feature request for a mobile app considering right-handedness and obfuscated clock.

**Comment by jas14** [comment] 2021-03-24 23:14
@wsobasik and @madivad , this is a duplicate of #760 - this feature has actually been in the mobile app since April 2018. It's under Preferences -> Clock. Hope this helps

**Closed** 2021-03-25 14:05 UTC
