### ISSUE TITLE
No response to tap

### ISSUE THREAD

**Issue by Robarookor2** [veloce/lichobile#1830] opened 2021-08-31 22:36 UTC
When you comment in the message feature during a timed game (timed in minutes) the response to tap commands as well as the accuracy of tap commanda is significantly reduced.

**Comment by maivincent** [comment] 2021-09-09 18:39
I have the same bug. After writing a message, it is very difficult to play as more than half of the taps do not work. Extremely annoying in the case of a timed game! I can't say thanks when someone accepts my takeback demand 😄 

I run Lichess v7.11.3, with Android 9 on OxygenOS 9.0.6.

**Comment by jas14** [comment] 2021-09-18 22:57
Probable duplicate of #1769

**Closed** 2021-09-18 22:59 UTC
