### ISSUE TITLE
Teams in App

### ISSUE THREAD

**Issue by iamthelara** [veloce/lichobile#1738] opened 2021-06-22 07:02 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hey, Dev ,Please add feature so we can access teams and tournaments from the lichess application.
Thank you.

**Comment by jas14** [comment] 2021-06-22 09:18
Duplicate of #1285

**Closed by jas14** 2021-06-22 09:18 UTC
