### ISSUE TITLE
Sounds only play after computer move

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#17] opened 2015-01-13 01:22 UTC
It plays two movement sounds at once but only after the computer's move.

This might be a bug.

Device: HTC Incredible S
OS: Android 4.4.4 w/ Cyanogen mod 11-20140919-UNOFFICIAL-vivo
Steps to reproduce: Played a KoTH game against AI lvl 3
Expected function: Sounds to play immediately after piece was placed.

**Comment by veloce** [comment] 2015-01-13 09:37
This is not a bug but I know move sounds could be handled properly. That's when the computed plays very fast; and sounds aren't correlated to pieces animations too.

On some devices (iphone6+) I noticed that disabling sound improved performance of UI.

**Comment by veloce** [comment] 2015-01-13 20:42
Might be fixed by above commit

**Closed** 2015-01-13 21:31 UTC
