### ISSUE TITLE
Castling causes a player piece to move on its own

### ISSUE THREAD

**Issue by kleo** [veloce/lichobile#1748] opened 2021-07-01 14:18 UTC
**Describe the bug**
Castling causes a player piece to move on its own on the next turn the board then freezes indefinitely. Restarting the application moves a player piece on its own and freezing again. 

This happens on either side of the board as the player at any time and I tried this on multiple Stockfish levels with the same result.

**To Reproduce**
1. Turn WiFi off
2. Start Lichess
3. Setup game with Stockfish
4. Castling on any time of the game causes a random player piece to move on its own.
5. Application freezes

**Expected behavior**
Play Lichess

**Screenshots**
![output](https://user-images.githubusercontent.com/13497504/124137995-ccd0b680-dab8-11eb-8add-4fef77e42225.gif)

**Smartphone:**
 - Device: Sony Xperia XZ1 Compact
 - OS: LineageOS 18.1 Android 11
- Lichess Android version:  v7.11.3

**Comment by jas14** [comment] 2021-07-01 20:56
Thanks for the report - this appears to be a duplicate of #1637

**Closed by jas14** 2021-07-01 20:56 UTC
