### ISSUE TITLE
Piece set are displaying on wild

### ISSUE THREAD

**Issue by B-anchor** [veloce/lichobile#1911] opened 2021-11-12 04:32 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment] 2021-11-12 11:58
What does "displaying on wild" mean? Please fill out the bug report template completely.

**Comment by B-anchor** [comment] 2021-11-12 17:04
On Fri, 12 Nov 2021, 14:58 Joe Stein, ***@***.***> wrote:

> What does "displaying on wild" mean? Please fill out the bug report
> template completely.
>
> —Chess pieces are wild looking not the normal pieces.
>
I have attached the pictures

**Comment by jas14** [comment] 2021-11-13 13:14
It doesn't look like any pictures made it to GitHub.

**Comment by B-anchor** [comment] 2021-11-13 19:05
> It doesn't look like any pictures made it to GitHub.

I have sent via email, it hard to attach the screenshot on GitHub may the the format

**Comment by B-anchor** [comment] 2021-11-13 19:11
> > It doesn't look like any pictures made it to GitHub.
> 
> I have sent via email, it hard to attach the screenshot on GitHub may the the format

My phone is oppo A5s

**Comment by jas14** [comment] 2021-11-13 21:20
Does it look like #1868 ?

**Comment by B-anchor** [comment] 2021-11-14 02:22
> Does it look like #1868 ?

Yes the same issue.

**Comment by jas14** [comment] 2021-11-14 02:50
Marking as duplicate of #1868 - please give that issue a thumbs-up so we can count who is affected

**Closed by jas14** 2021-11-14 02:50 UTC
