### ISSUE TITLE
Performance stats page should not say "[y]our rating" when looking at the stats for another player

### ISSUE THREAD

**Issue by doughepi** [veloce/lichobile#1978] opened 2022-01-10 17:29 UTC
**Describe the bug**
When viewing the game variant statistics page of _another_ user, you are met with a "Your rating" heading. While this is not a limiting bug, I believe it would be in the best interests of the user experience to say something like "[User]'s rating" or "Current rating" instead. [This was actually the case way back before i18n was implemented.](https://github.com/veloce/lichobile/commit/6c89df2b3b34d73f8ba68884b8e317bc71e68056#diff-2971e930da274c9548205762418e911e6fe4d055795724e3b7ae11ac442f0ea0L56)

I would be happy to submit a pull request with the proposed changes.

**To Reproduce**
1. Go to the page of another user.
2. Click one of the game variant types.
3. Observe the "Your rating" section header.

**Expected behavior**
The aforementioned section header should say "[User]'s rating" or "Current rating".

**Screenshots**

Note, my username is `doughepi` and this screenshot is me observing another players statistics.
![1021A4DD-2BEC-4D72-BE6D-83793B3AD378_1_201_a](https://user-images.githubusercontent.com/14059149/148810173-c73ff2f4-4c38-40ac-adc5-3416358d30ff.jpeg)

**Smartphone (please complete the following information):**
 - Device: All Devices
 - OS: All Operating Systems
 - Browser All Browsers
 - Version >= 7.9.0

**Comment by jas14** [comment] 2022-01-10 18:59
@doughepi thanks for the detailed report - I'm closing this as a duplicate of #1879 but PRs are appreciated!

**Closed by jas14** 2022-01-10 18:59 UTC
