### ISSUE TITLE
[Android] Excessive battery drain

### ISSUE THREAD

**Issue by danarnold** [veloce/lichobile#313] opened 2016-04-11 19:45 UTC
The app uses a very large amount of battery power, even more than the Screen, which should be using the most battery. The app was hardly used during this time. [Photo link](http://i.imgur.com/jFj9oGS.png)

Phone is Nexus 6P, stock Android 6.0.1 MHC19I.

**Comment by veloce** [comment] 2016-04-11 21:11
Should be fixed in next version.

**Comment by JoelMon** [comment] 2016-04-11 21:11
I have the same exact problem. Nexus 4.

**Comment by veloce** [comment] 2016-04-17 15:51
Closing since the problem as been fixed. You'll tell me if the issue is still here in version 3.0

**Comment by danarnold** [comment] 2016-04-17 19:42
I'll be sure to let you know, as soon as I can get version 3.0 running. I tried building it myself using the instructions in the README and `tarifa build android`, but upon install I get "Resource not found. Resource not found." in a toast, and it fails to log in or do anything requiring server configuration. Maybe I had to modify env.json and not just copy the sample file? If so, I'm not sure how to modify it. Either way, perhaps you could build a new release.

**Comment by veloce** [comment] 2016-04-18 08:23
https://github.com/veloce/lichobile/wiki/lichess.org-mobile-application-for-android-and-iOS

There is a beta of 3.0: you can get it here: http://bit.ly/1RwrCV4

Let me know any bug you may find :)

**Comment by danarnold** [comment] 2016-04-18 15:51
Great, thanks. I just installed it and I'll follow up if there are any issues.

**Comment by PatDeLux** [comment] 2016-05-13 20:43
For me the issue has reappeared (or is still there) in 3.1.0  
It seems that the app does not really close on exit, and by the end of the day, it eats up to 48% of battery while I just played 10 min the morning and 15 min at lunch time. 
I have to go to the battery usage screen and explicitly close the program to avoid that drain.

**Comment by veloce** [comment] 2016-05-14 10:04
I don't have this problem myself (I'm on android 5).

is it correlated to network usage? what was the last screen you were in before exiting the app?

**Comment by JoelMon** [comment] 2016-05-15 21:01
Something that happens with me is that I may be on Reddit or something else and the "Lichess network can not be reached" message pops up without me being on the app.

**Comment by veloce** [comment] 2016-05-15 23:15
hmm. ok that is not normal of course. your app is in background then I suppose?

**Comment by PatDeLux** [comment] 2016-05-16 15:07
I tried to observe the behaviour these last days. No problems except for today (see below).
The only things I use are the "problem of the day" or Create a game against the computer. I always quit using the Home button.
Perhaps an indicator in the notification bar could show if the app is still running, a bit like Waze ?
![unspecified](https://cloud.githubusercontent.com/assets/4831319/15293365/ea75cad6-1b87-11e6-90e4-b05eb6b5528e.png)

**Comment by veloce** [comment] 2016-05-24 20:30
Was able to see the issue with mobile data and not wifi.

**Comment by veloce** [comment] 2016-06-01 10:42
Ok, after some more tests I found the issue: it was the connectivity `online` event that triggered in background, was restarting socket connection.

**Closed** 2016-06-01 10:41 UTC
Labels: bug
