### ISSUE TITLE
Network issues

### ISSUE THREAD

**Issue by tcelestin-profideo** [veloce/lichobile#1681] opened 2021-05-12 13:20 UTC
**Describe the bug**
It started a few weeks ago. When using the app, the number of players and games appear as a "?", same for the Ping ans Server information from the top left menu.

This is not really a problem, except I'm experiencing infinite loading on daily games. When I open one of them, there are 3 yellow dots on top of the game that keep loading, and when I play my move, the validation loads indefinitely as well. The only workaround I found was to enter Analysis mode, play my move there and add the variant.

I tried on wifi network, mobile network, and even with a VPN. I'm using a Fairphone with /e/OS (which blocks Google stuff for example), don't know if you added something recently that might interfere.

**To Reproduce**
I'm not really sure, I only have the symptoms :/

**Expected behavior**
Informations on home screen to appear + daily games that finish loading and let me play my move one the usual screen.

**Screenshots**
![Screenshot_20210512-151320_lichess](https://user-images.githubusercontent.com/54313790/117981522-612e6080-b335-11eb-8da8-31a737765388.png)
![Screenshot_20210512-151335_lichess](https://user-images.githubusercontent.com/54313790/117981526-61c6f700-b335-11eb-8b29-3a9650509b0b.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone3
 - OS: /e/OS 0.16

**Comment by jas14** [comment] 2021-05-12 13:31
@tcelestin-profideo thank you for the report. This appears to be a duplicate of issue #1599, which is active with other commenters who are experiencing the same problem. Would you mind closing this issue and joining that one instead?

**Comment by tcelestin-profideo** [comment] 2021-05-12 13:34
Right, I'll participate on the other one, sorry ^^

**Closed** 2021-05-12 13:34 UTC
